### ISSUE TITLE
Uri::resolve doesn't pass RFC tests

### ISSUE THREAD

**Issue by jeremeamia** [guzzle/psr7#1]
I [borrowed the RFC3986 tests](https://github.com/guzzle/psr7/blob/master/tests/UriTest.php#L113) from  Guzzle, and two of them aren't passing for the `resolve` method. There is also, what looks like, some code duplication in the `resolve` logic, so we should take look at it's implementation.

**Comment by mtdowling** [comment]
Ok, let's fix the failing tests. Which ones are they?

**Comment by mtdowling** [comment]
Looks like it was just one case that isn't relevant based on the PSR
