### ISSUE TITLE
cURL error 3

### ISSUE THREAD

**Issue by garyblankenship** [guzzle/psr7#102]
a composer update broke our use of guzzlehttp, when updating to psr7 1.3.1
forcing our composer.json file to install 1.3.0 got it working for us again.

the exception thrown is:
"cURL error 3: <url> malformed (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)"

the url is like http://10.10.20.20:2080/api/cars/1

edit: broken with commit 889f21e

**Comment by Tobion** [comment]
Could you provide a failing test case? I don't see how 889f21e is related to your failing URI.
There must be something else going on.
If you cannot provide a failing test case please describe what you're doing.

**Comment by Tobion** [comment]
I could image your URI is not actually `http://10.10.20.20:2080/api/cars/1` but `10.10.20.20:2080/api/cars/1` which is not a correctly formed URI with a host. If you fix your URI it should work correctly.

**Comment by dgafka** [comment]
Why it doesn't use http wrapper as default one? 
I think, that this commit just broke a lot of libraries.

**Comment by garyblankenship** [comment]
Tobion, here's how I was using it.

`$client = new GuzzleHttp\Client( [
    'base_uri' => 'http://10.10.20.20:2080',
    'headers'  => ['Accept' => 'application/json'],
    'timeout'  => 10
] );

$response = $client->get('/api/cars/1');`

**Comment by Tobion** [comment]
@garyblankenship your base URI is not `'http://10.10.20.20:2080'` as I'm sure it does not include the scheme in your case. This is why this error appear.
I'm fixing this.

**Comment by Tobion** [comment]
See guzzle/guzzle#1509 for a fix.
