### ISSUE TITLE
UriResolver does not look at host when scheme is present

### ISSUE THREAD

**Issue by pkruithof** [guzzle/psr7#114]
When resolving a path for a base url, the combination of the guzzle package and this one results in the host not being set at all.

To explain: the [buildUri method](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L148) in the Guzzle Client always ensures a scheme. So if you have the following base/rel uri:

```php
$base = new Uri('http://example.org');
$rel = new Uri('/foo'); # does not have a scheme
```

If you request `$rel` with Guzzle, and you have middleware that uses the resolve method to make a proper uri out of the two:

```php
# in middleware, $rel now has a scheme added by Guzzle
$uri = Uri::resolve($base, $rel);
```

You would expect this to yield `http://example.org/foo`, yet the resolver checks for a scheme in `$rel` and if so, assumes the host is set and returns the normalized `$rel` without looking at the base uri:

https://github.com/guzzle/psr7/blob/64862e854f876bc5aee2996cab2f552db8586065/src/UriResolver.php#L69-L71

Which results in a uri without a host. Now I don't think it's incorrect that the scheme is added by Guzzle, which is why I create the issue in this repo instead. I think the resolve method should check for both scheme **and** host in the if statement I linked here above.

**Comment by pkruithof** [comment]
ping @mtdowling @Tobion

**Comment by Tobion** [comment]
From what I infer from your description is that you are not using the Guzzle `base_uri` config option but instead have your own middleware that resolves the `/foo` URI?
And in your middleware you will receive `http:/foo` as URI due to the added scheme.

The `resolve` method should not be changed because it is according to a standard. What we can change is that the `http` scheme in https://github.com/guzzle/guzzle/blob/master/src/Client.php#L148 is only added if the URI has a host at all.

**Comment by pkruithof** [comment]
> From what I infer from your description is that you are not using the Guzzle base_uri config option but instead have your own middleware that resolves the /foo URI?

Correct.

> What we can change is that the http scheme in https://github.com/guzzle/guzzle/blob/master/src/Client.php#L148 is only added if the URI has a host at all.

That would be great, yes. Should I open a new issue in that repo?

**Comment by Tobion** [comment]
Feel free to create a PR. The change is really simple.

**Comment by pkruithof** [comment]
Right, done: https://github.com/guzzle/guzzle/pull/1565
