### ISSUE TITLE
CURL CA certificate, where to set?

### ISSUE THREAD

**Issue by paulcanning** [guzzle/psr7#120]
This library is being included by Google Cloud API and I am getting errors about there being no CA Cert. Fair enough.

However, I have no idea where I can set the location of the certificate, or how to state that I don't want ot use one.

I've had to kludge the library and set all CA Cert settings to `false` - obviously no the best idea.

**Comment by Tobion** [comment]
The CA Cert is about the HTTP client at https://github.com/guzzle/guzzle
Please open an issue there. PSR-7 is only about the request/response implemenation.

**Comment by Tobion** [comment]
For documentation about the cert option, see http://guzzle.readthedocs.io/en/latest/request-options.html#cert
