### ISSUE TITLE
Array Parameter not working

### ISSUE THREAD

**Issue by raphcadiz** [guzzle/psr7#121]
I have this code

`$data = array(
	'File-Name' => $file_name,
	'Mime-Type' => 'application/pdf',
	'File' => $sourcePath
);
$multipartStream = new MultipartStream($data);`

but I'm getting an error of
Catchable fatal error: Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given, called in /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/guzzlehttp/psr7/src/MultipartStream.php on line 70 and defined in /Applications/MAMP/htdocs/adobesignwp/wp-content/plugins/Gravity2PDF/lib/vendor/guzzlehttp/psr7/src/MultipartStream.php on line 79

**Comment by Tobion** [comment]
The constructor expects an array of associative arrays as documented in https://github.com/guzzle/psr7/blob/master/src/MultipartStream.php#L17
For examples, see https://github.com/guzzle/psr7/blob/master/tests/MultipartStreamTest.php
