### ISSUE TITLE
copy_to_stream() should return count of copied bytes

### ISSUE THREAD

**Issue by umesecke** [guzzle/psr7#122]
The function copy_to_stream() should return the count of copied bytes. Like the PHP function stream_copy_to_stream() does.

Current workaround is to use copy_to_string() and check the length of the returned string but this does not play well for large amounts of data.

**Comment by Tobion** [comment]
Can you give us a use-case this is helpful for please?

**Comment by umesecke** [comment]
It'd like to keep track of the amount of copied data and in my case send that number to statsd. As there might be less (or even more) than the requested length (`$maxLen`) of data copied I'd like to know the exact amount.

I could implement a stream decorator that counts the amount of written data but this doesn't seem to me as the right approach.

**Comment by Tobion** [comment]
Closing as there does not seem enough interest in this from others. Also there is an alternative solution mentioned.
