### ISSUE TITLE
ServerRequest::getUriFromGlobals() does not set the Scheme correctly when it is HTTP

### ISSUE THREAD

**Issue by ksandell** [guzzle/psr7#130]
For Guzzle ^6.2, the following code in the function getUriFromGlobals() does not appear to set the scheme correctly when it is HTTP:
```php
    // file="GuzzleHttp/Psr7/src/ServerRequest.php"

    public static function getUriFromGlobals() {
        $uri = new Uri('');

        if (isset($_SERVER['HTTPS'])) {
            $uri = $uri->withScheme($_SERVER['HTTPS'] == 'on' ? 'https' : 'http');
        }
    ....
```
My understanding and results show that if the scheme is HTTP then no $uri scheme is set at all.

### Fix suggestion
My suggestion for a fix is to add an else statement for the if like this:
```php
    public static function getUriFromGlobals() {
        $uri = new Uri('');

        if (isset($_SERVER['HTTPS'])) {
            $uri = $uri->withScheme($_SERVER['HTTPS'] == 'on' ? 'https' : 'http');
        } else {
            $uri = $uri->withScheme('http');            
        }
    ....
```
### Other effects
This was discovered when using the fromGlobals() to populate a ServerRequest with the request details and displaying the value of $serverRequest->getUri(). The resulting string is strangely formatted, starting with no scheme and only a // and containing the port number 80 as well. With the fix the Uri looks normal (showing scheme and not hiding port 80).

Example wrong: `//domain.com:80/path/document?query=value`
Example right: `http://domain.com/path/document?query=value`

_Test system: Apache/2.4.25 (Win64) OpenSSL/1.0.2j PHP/7.1.1 (on Windows 10)_

**Comment by ksandell** [comment]
Seems a pull request for this already exists: https://github.com/guzzle/psr7/pull/128/commits/9d5194ac808f8cc245d151149520a9559a70dc2f

**Comment by rafaelbeckel** [comment]
`$_SERVER('HTTPS')` is not a safe way to detect the scheme, especially if the script is behind a load balancer.

I had the same problem here, and the 'https' scheme was sent by Nginx as 'X-Forwarded-Proto', so the current implementation detected my `https://` call as `http://`.

According to Mozilla, this key is a de-facto standard:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

In the same page, we can see there are possibly some other values:
~~~bash
# Microsoft
Front-End-Https: on

X-Forwarded-Protocol: https 
X-Forwarded-Ssl: on 
X-Url-Scheme: https
~~~
