### ISSUE TITLE
MultipartStream response

### ISSUE THREAD

**Issue by veewee** [guzzle/psr7#141]
Hello,

Currently the MultipartStream can be used to build requests. However, when a response contains a multipart message, it is a tedious work to parse the content back to the different elements. 
It would be great if there was a stream that could manage the different parts in a multipart response.

In my imagination, it looks something like:
```php
class MultipartResponseStream
{
    public function getElements() : MultiPartCollection;
    public function getBoundary() : string;
}

class MultiPartCollection
{
   public function getElementByContentId(string $contentId) : MultiPartElement;
   public function filterByContentType(string $contentType) : MultiPartCollection;
}

class MultiPartElement
{
    public function getHeaders() :  string[][] ;
    public function hasHeader($header) : bool;
    public function getHeader($header) : [];
    public function getHeaderLine($header) : string;
    public function getBody() : StreamInterface;
}
```

When the Content-Type header of the response matches `multipart/*`, the response could be MultipartResponseStream. Is this something that would be a nice addition or do you see it differently?

**Comment by smatyas** [comment]
This lib. can be useful in the meantime: https://github.com/Riverline/multipart-parser

**Comment by GrahamCampbell** [comment]
Thanks for the issue. This is out of scope of what this package is for I'm afraid.
