### ISSUE TITLE
Increased response time on psr7 update

### ISSUE THREAD

**Issue by saishsali** [guzzle/psr7#144]
### Summary of problem
I'm using guzzle HTTP/guzzle bundle version 5.3.0 which use psr7 version 1.3.0 and elasticsearch-php bundle version 5.3.1 in project. On updating the guzzle bundle to version 6.2.3 (which requires psr7 version >= 1.3.1), the response time of the search being done using elastic search increases significantly (from 13 ms to 170 ms). Any idea what might be the reason behind the increase in response time? I'm using signing handler as follows:

```php
    private function signingHandlerForEs()
    {
        $psr7Handler = Aws\default_http_handler();
        $signer = new SignatureV4('es', 'ap-southeast-1');
        $credentialProvider = $this->getCredentialProvider();

        return function (array $request) use ($psr7Handler, $signer, $credentialProvider) {
            $request['headers']['host'][0] = parse_url($request['headers']['host'][0], PHP_URL_HOST);

            $psr7Request = new Request(
                $request['http_method'],
                (new Uri($request['uri']))
                    ->withScheme($request['scheme'])
                    ->withHost($request['headers']['host'][0]),
                $request['headers'],
                $request['body']
            );

            $signedRequest = $signer->signRequest(
                $psr7Request,
                call_user_func($credentialProvider)->wait()
            );

            $response = $psr7Handler($signedRequest)->wait();

            return new CompletedFutureArray([
                'status' => $response->getStatusCode(),
                'headers' => $response->getHeaders(),
                'body' => $response->getBody()->detach(),
                'transfer_stats' => ['total_time' => 0],
                'effective_url' => (string) $psr7Request->getUri(),
            ]);
        };
    }
```

### System details
- Operating System: Ubuntu
- PHP Version : 7.0.4
- ES-PHP client version : 5.3.1 
- Elasticsearch version : Amazon elasticsearch (https://aws.amazon.com/elasticsearch-service/)

**Comment by Tobion** [comment]
Pretty sure this is not related to guzzle/psr7 as there are no performance relevant changes. I'm afraid you need to debug and profile this yourself. I can recommend https://blackfire.io/ for that. Just do one profile before and one after the update. Then you'll see the source problem.
