### ISSUE TITLE
Verbose Http status code

### ISSUE THREAD

**Issue by denormalizer** [guzzle/psr7#150]
I would like to have the ability to use verbose status codes:

    $statusCode = Response::OK; // returns 200
    $statusCode = Response::NOT_FOUND; // returns 404

I have seen other libraries implement this, is there a way to do this in guzzle? If not, is this something useful that should be implemented in guzzle?

**Comment by Konafets** [comment]
Have a look at [Teapot](https://github.com/shrikeh/teapot).

**Comment by Tobion** [comment]
There is also https://github.com/php-fig/http-message-util

As there are already solution I'm closing this for now.

**Comment by denormalizer** [comment]
I did have a brief look at Teapot but I thought it was a bit heavy for my needs.

I hadn't seen `http-message-util` but it seems like what I will use (after using a different utility).
