### ISSUE TITLE
ServerRequest::getUriFromGlobals() results Uri with wrong query string for url https://site.com/path?continue=https://site.com/widget?param=1

### ISSUE THREAD

**Issue by idealogica** [guzzle/psr7#151]
For url https://site.com/path?continue=https://site.com/widget?param=1
`\GuzzleHttp\Psr7\ServerRequest::getUriFromGlobals()->getQuery()` results `continue=https://site.com/widget`.
Expected result: `continue=https://site.com/widget?param=1`

**Comment by sagikazarmark** [comment]
IMO for that to work you would have to urlencode `https://site.com/widget?param=1`

**Comment by GrahamCampbell** [comment]
For reference:

![image](https://user-images.githubusercontent.com/2829600/27460002-23eec930-57a9-11e7-95e9-b785af24c743.png)

**Comment by idealogica** [comment]
1. I get that kind of request form external service, I can't urlencode query param
2. Internal PHP parser parses the url to $_GET correctly:
```array:1 [▼
  "continue" => "https://site.com/widget?param=1"
]```
3. The fix I offer is very simple and quick and it doesn't affect older code that uses ServerRequest::getUriFromGlobals() method.

**Comment by Nyholm** [comment]
What about this url?
`https://site.com/path?continue=https://site.com/widget?param=1&foo=bar`

Should it be (A) `https://site.com/widget?param=1&foo=bar` or (B) `https://site.com/path?continue=[url]&foo=bar` ?

You should tell the external service to urlencode the param (or give them an URL encoded string in the external service settings).

**Comment by idealogica** [comment]
@Nyholm  it is not a matter of the reported issue how to parse query string. The query string for url `https://site.com/path?continue=https://site.com/widget?param=1&foo=bar` should be `continue=https://site.com/widget?param=1&foo=bar`. In case of using `ServerRequest::getUriFromGlobals()` it is `continue=https://site.com/widget`. 
Btw the behaviour of php internal parser looks much more logical: 
```
array:2 [▼
  "continue" => "https://site.com/widget?param=1"
  "foo" => "bar"
]
```

**Comment by sagikazarmark** [comment]
> should be `continue=https://site.com/widget?param=1&foo=bar`
> Btw the behaviour of php internal parser looks much more logical:

I feel a little bit of contradiction here.

Nevertheless, I think the fix you provided should be merged anyway.
