### ISSUE TITLE
Get headers from $_SERVER when getallheaders() is not available?

### ISSUE THREAD

**Issue by courtney-miles** [guzzle/psr7#157]
In `ServerRequest::fromGlobals()` the request headers are fetched only if the `getallheaders()` function exists ([src/ServerRequest.php:169](https://github.com/guzzle/psr7/blob/811b676fbab9c99e359885032e5ebc70e442f5b8/src/ServerRequest.php#L169))

I believe this function only exists if you are running PHP under Apache with mod_php.

Is the expectation that everyone should implement their own copy of this function, rather than for Guzzle implement it's own solution?

If not, I would be happy to submit a PR for Guzzle to get the values from `$_SERVER` when `getallheaders()` does not exist.

**Comment by jk2K** [comment]
there is a pull request, https://github.com/guzzle/psr7/pull/162

**Comment by courtney-miles** [comment]
Closing in favour of #162
