### ISSUE TITLE
`ServerRequest::fromGlobals` prevents inheritance

### ISSUE THREAD

**Issue by kael-shipman** [guzzle/psr7#159]
`fromGlobals` instantiates object by name, rather than using `static` keyword. This means that if you create a derivative class, you must completely overwrite the `fromGlobals` method to use it.

**Comment by jeskew** [comment]
There's a bit of discussion on #158 as to why `static` is not used. To summarize: `Psr\Http\Message\ServerRequestInterface` does not require any particular constructor signature, so invoking the constructor via late static binding is unsafe.

**Comment by Tobion** [comment]
Closing as explained.
