### ISSUE TITLE
Send post request returns exception

### ISSUE THREAD

**Issue by developersunzhichao** [guzzle/psr7#163]
Send post request returns 

object(GuzzleHttp\Psr7\Stream)#300 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(332) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> NULL ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } }

**Comment by Tobion** [comment]
The body of a response is a stream. You can cast it to string `(string) $response->getBody()` to get the response content.
