### ISSUE TITLE
Composer->autoload->files breaks PHP 5.3 installs

### ISSUE THREAD

**Issue by slaFFik** [guzzle/psr7#171]
Composer `autoload` setting: `"files": ["src/functions_include.php"]` - this contradicts with the `require` section `"php": ">=5.4.0"` rule, because of the PHP 5.4 code used in functions, that are always included, regardless of `"php": ">=5.4.0"`.

That means that projects that are PHP 5.3+ and require this library - will be broken.

It always loads that file, even if composer install is done on PHP 5.3 server.

**Comment by Tobion** [comment]
I don't get what you're trying to say. But this package requires PHP 5.4 so it won't work with 5.3 obviously.

**Comment by sagikazarmark** [comment]
Sounds invalid to me.
