### ISSUE TITLE
Post form with GuzzleHttp\Psr7\Request not working

### ISSUE THREAD

**Issue by MateYoutility** [guzzle/psr7#179]
I use this Library with Laravel.

When i use **GuzzleHttp\Psr7\Request** class with **GuzzleHttp\Pool** class, the library doesn't put my params into form_params.

example:
```php
$requests = [];

$request = new Request('POST', 'https://httpbin.org/post', [
    "form_params" => [
        "a" => "b",
        "c" => "d"
    ]
]);

$requests[] = $request;

$client = new Client();

$pool = new Pool($client, $requests, [
    'concurrency' => 5,
    'fulfilled' => function ($response, $index)
    {
        echo "result: ".$response->getBody();
    },
    'rejected' => function ($reason, $index)
    {
        echo "error";
    },
]);

$promise = $pool->promise();
$promise->wait();
```
my response (see form key):
```json
result: {
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Connection": "close", 
    "Content-Length": "0", 
    "Form-Params": "d", 
    "Host": "httpbin.org", 
    "User-Agent": "GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.2.0-1+ubuntu16.04.1+deb.sury.org+1"
  }, 
  "json": null, 
  "origin": "85.37.44.218", 
  "url": "https://httpbin.org/post"
}
```

---

When i use the **GuzzleHttp\Client** class it work

example:
```php
$client = new Client();

$response = $client->post('https://httpbin.org/post', [
    "form_params" => [
        "a" => "b",
        "c" => "d"
    ]
]);

echo "response: ".(string) $response->getBody()."\n";
```

my response (see form key):
```json
response: {
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "a": "b", 
    "c": "d"
  }, 
  "headers": {
    "Connection": "close", 
    "Content-Length": "7", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.2.0-1+ubuntu16.04.1+deb.sury.org+1"
  }, 
  "json": null, 
  "origin": "85.37.44.218", 
  "url": "https://httpbin.org/post"
}
```

**Comment by Tobion** [comment]
You confused request headers with client options.

form_params is a client open for sending the request. see 

https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/RequestOptions.php#L119

In contrast `new Request('POST', 'https://httpbin.org/post', [ "form_params" => []])` is just adding a header named "form_params".

So the two examples you gave do not do the same thing. To use the same thing in the request class you can set the body of the request similar to

https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/Client.php#L310

**Comment by msaus** [comment]
I have same issue here.
How can I solve it by using that?

**Comment by NauDev306** [comment]
> 
> 
> You confused request headers with client options.
> 
> form_params is a client open for sending the request. see
> 
> https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/RequestOptions.php#L119
> 
> In contrast `new Request('POST', 'https://httpbin.org/post', [ "form_params" => []])` is just adding a header named "form_params".
> 
> So the two examples you gave do not do the same thing. To use the same thing in the request class you can set the body of the request similar to
> 
> https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/Client.php#L310

This was the same as my issue (guzzle/guzzle - https://github.com/guzzle/guzzle/issues/2456)

;) You were right...no issue with guzzle @Nyholm

**Comment by zayaets** [comment]
@Tobion Thank you!

**Comment by saurabh12231978** [comment]
> You confused request headers with client options.
> 
> form_params is a client open for sending the request. see
> 
> https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/RequestOptions.php#L119
> 
> In contrast `new Request('POST', 'https://httpbin.org/post', [ "form_params" => []])` is just adding a header named "form_params".
> 
> So the two examples you gave do not do the same thing. To use the same thing in the request class you can set the body of the request similar to
> 
> https://github.com/guzzle/guzzle/blob/73bf0937061461ca45292a93aa3b7e9010f2e753/src/Client.php#L310

I was also facing similar issue; this answer fixed...btw Guzzle documentation is very poor specially for PSR7, BatchPool etc

**Comment by Nyholm** [comment]
I am happy to receive PRs to improve the documentation.
