### ISSUE TITLE
Stream is treated as not readable if opened in "wb+" mode

### ISSUE THREAD

**Issue by devbazilio** [guzzle/psr7#183]
https://github.com/guzzle/psr7/blob/master/src/Stream.php#L22

http://www.cplusplus.com/reference/cstdio/fopen/
http://man7.org/linux/man-pages/man3/fopen.3.html
both docs says:

With the mode specifiers above the file is open as a text file. In order to open a file as a binary file, a "b" character has to be included in the mode string. This additional "b" character can either be appended at the end of the string (thus making the following compound modes: "rb", "wb", "ab", "r+b", "w+b", "a+b") **or be inserted between the letter and the "+" sign for the mixed modes** ("rb+", "wb+", "ab+").

**Comment by zvinger** [comment]
+1 have same issue. Solved by adding 
```
'rb+' => true
```
to vendor/guzzlehttp/psr7/src/Stream.php:22 in read array. This problem is in PHP 7.1.

**Comment by Tobion** [comment]
Thanks for the research. Would you mind creating a PR with a test?

**Comment by zvinger** [comment]
I'll try to make it) I didn't make any PR before)

**Comment by prisis** [comment]
If you like you can use this, with \preg_match(self::READABLE_MODES, $meta['mode'])

```php
    /**
     * Resource modes.
     *
     * @var string
     *
     * @see http://php.net/manual/function.fopen.php
     * @see http://php.net/manual/en/function.gzopen.php
     */
    public const READABLE_MODES = '/r|a\+|ab\+|w\+|wb\+|x\+|xb\+|c\+|cb\+/';

    public const WRITABLE_MODES = '/a|w|r\+|rw|x|c/';
```

**Comment by prisis** [comment]
Yes, it's from https://github.com/narrowspark/framework/blob/master/src/Viserio/Component/Http/Stream.php if you like, you can copy the tests too
