### ISSUE TITLE
Duplicate requests when "withMethod" or other similar methods are used

### ISSUE THREAD

**Issue by Emulator000** [guzzle/psr7#185]
I'm experiencing an issue with the "withMethod" method:
https://github.com/guzzle/psr7/blob/41972f428b31bc3ebff0707f63dd2165d3ac4cf6/src/Request.php#L92

In some circumstances we had an issue with duplicate requests being made on the recipient server.

PHP Version: 7.0.24
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

Example of use:
```
$client = new Client();

$request = new Request('POST', 'http://www.google.it/', []);
$request = $request->withMethod('GET');
$response = $client->send($request);
```

**Comment by Tobion** [comment]
The example you gave only sends a single request. You need to provide more details or a reproducer if you really think there is a bug in guzzle.
