### ISSUE TITLE
Syntax Error, array default value 

### ISSUE THREAD

**Issue by blasco991** [guzzle/psr7#188]
PHP Parse error: syntax error, unexpected '[' in /usr/local/psa/admin/plib/modules/wp-toolkit/vendor/guzzlehttp/psr7/src/functions.php on line 78

**Comment by prisis** [comment]
What version of PHP are you using?

**Comment by blasco991** [comment]
its from the wp-toolkit included in plesk panel, i didn't check at the moment

**Comment by prisis** [comment]
Switch to php5.4 and it should work for you :) (i dont know what php version plesk panel with wp-toolkit is using)

**Comment by sagikazarmark** [comment]
It definitely looks like that short array syntax is causing the problem which was added in PHP 5.4.

Closing for now, feel free to reopen if it turns out to be something else.
