### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/psr7#20]
Is another tag planned in the near future. It's also necessary for people using old versions of composer.

**Comment by mtdowling** [comment]
Yes. It would be next week if I tag it because I'm going out of town. @jeremeamia or @jeskew might tag it before that (to make a release, you just need to update the changelog and push a tag).

**Comment by GrahamCampbell** [comment]
:)

**Comment by mtdowling** [comment]
tagged 1.1.0
