### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/psr7#200]
@guzzle/maintainers , @Tobion what do you think about tagging 1.5.0?

I know there is an ongoing discussion about dropping 5.5 support, but there is a considerable number of unreleased changes.

**Comment by Tobion** [comment]
I'm in the process of working off issues. I'll finish #194 and #178 and will then create the 1.5 tag.

**Comment by sagikazarmark** [comment]
Great, thanks!

**Comment by GrahamCampbell** [comment]
If the current master represents what will become 1.5.0, then the branch alias should be 1.5-dev. :)

---

https://github.com/guzzle/psr7/pull/206

**Comment by GrahamCampbell** [comment]
Is there anything I can do to help you guys with reviewing stuff on this repo?

**Comment by GrahamCampbell** [comment]
Is there anything I can do to help you guys with reviewing stuff on this repo?

**Comment by sagikazarmark** [comment]
An extra pair of eyes never hurt. 😉 

My priority now is to get 1.5 out ASAP, for that @Tobion has two blocker(?) issues.

**Comment by sagikazarmark** [comment]
I created a milestone to follow the 1.5.0 version: https://github.com/guzzle/psr7/milestone/1

Any chance we can get this done by the end of the month?

@Tobion ?

**Comment by Tobion** [comment]
Sorry I didn't have time. Feel free to step in.

**Comment by Nyholm** [comment]
I reviewed those issues a while back. Im happy with them. But I need a second review.

**Comment by Tobion** [comment]
I will release 1.5 tomorrow or so.

**Comment by sagikazarmark** [comment]
See https://github.com/guzzle/psr7/releases/tag/1.5.0
