### ISSUE TITLE
How to emit a response?

### ISSUE THREAD

**Issue by plashenkov** [guzzle/psr7#204]
Hi!

Now we have ServerRequest::fromGlobals().

But how can we emit a response? Emit headers, body, etc.
Would be nice to have something like ResponseEmitter class or some helper function (sorry if I missed something and something like this already exists).

Some links which can be helpful:
1. https://github.com/zendframework/zend-diactoros/blob/master/src/Response/SapiEmitter.php#L13
2. https://github.com/slimphp/Slim/blob/e84150bfbb0db0209bc940554decfde89cc251b5/Slim/App.php#L421

**Comment by prisis** [comment]
Hey :) if you using php 7.1 you can try my package https://packagist.org/packages/narrowspark/http-emitter

**Comment by sagikazarmark** [comment]
Guzzle is an HTTP *Client*, so the server side is not necessarily the main concern. That being said, I'm not against having a super simple emitter here. Feel free to open a PR.

**Comment by sagikazarmark** [comment]
Actually I just needed the same thing, so there might be some simple emitting logic added to this package as well. 😉

**Comment by plashenkov** [comment]
Well, I can try to add a PR. Do we need some separate class for that? Or maybe a function? How should we name it?

ResponseEmitter? ResponseSender?

**Comment by sagikazarmark** [comment]
A separate class would be nice, ResponseEmitter sounds good.

You could borrow some ideas from here: https://github.com/zendframework/zend-diactoros

**Comment by plashenkov** [comment]
Yep, I already attached about the same link above.

**Comment by plashenkov** [comment]
I've added ResponseEmitter class: https://github.com/guzzle/psr7/pull/208
Hope it's fine.

**Comment by tflori** [comment]
IMHO it should be a helper function - not a class. 

https://github.com/http-interop/response-sender has one release, only one contributor and 22k installations. the implementation is so simple that there are no questions at all:

```php
/**
 * Send a HTTP response
 *
 * @return void
 */
function send(ResponseInterface $response)
{
    $http_line = sprintf('HTTP/%s %s %s',
        $response->getProtocolVersion(),
        $response->getStatusCode(),
        $response->getReasonPhrase()
    );
    header($http_line, true, $response->getStatusCode());
    foreach ($response->getHeaders() as $name => $values) {
        foreach ($values as $value) {
            header("$name: $value", false);
        }
    }
    $stream = $response->getBody();
    if ($stream->isSeekable()) {
        $stream->rewind();
    }
    while (!$stream->eof()) {
        echo $stream->read(1024 * 8);
    }
}
```
