### ISSUE TITLE
ServerRequest::fromGlobals() should use `new static()`

### ISSUE THREAD

**Issue by bkdotcom** [guzzle/psr7#212]
Currently:

```
class MyExtendedRequest extends \GuzzleHttp\Psr7\ServerRequest
{
}

// This creates a ServerRequest object, not a MyExtendedRequest object :(
$request = MyExtendedRequest::fromGlobals(); 
``` 

fromGlobals calls `new ServerRequest(...)`.  it should call `new static(...)`
Workaround is for extended class to extend (recreate) the fromGlobals method (but with static)

**Comment by sagikazarmark** [comment]
This has been rejected once. Please see #158 and #159 for explanations.

**Comment by sagikazarmark** [comment]
@bkdotcom What about plain old functions?

```php
function isXhr(ServerRequestInterface $request)
{
    return true;
}
```

IMO that fits better your use case since it would work with any implementation and you don't have to check or make sure that the request is always your request type.
