### ISSUE TITLE
composeComponents Error!

### ISSUE THREAD

**Issue by ManiakMill** [guzzle/psr7#220]

**Comment by ManiakMill** [comment]
UriResolver:
`return new Uri(Uri::composeComponents(
            $base->getScheme(),
            $targetAuthority,
            $targetPath,
            $targetQuery,
            $rel->getFragment()
));`

Call to undefined method GuzzleHttp\Psr7\Uri::composeComponents()

**Comment by Tobion** [comment]
The method exists: https://github.com/guzzle/psr7/blob/23e7d3812a82bdbff4a5cb8e4628bcc06eec5d68/src/Uri.php#L114

Please give provide the code to reproduce your problem or please explain how you got this error.

**Comment by Tobion** [comment]
Maybe you have an outdated opcache that you need to clear.
