### ISSUE TITLE
eof not reached for streams created from strings

### ISSUE THREAD

**Issue by phpbg** [guzzle/psr7#222]
Streams are affected by https://bugs.php.net/bug.php?id=77146

You can reproduce it with a unit test:
```php
$data = "foo";
$stream = \GuzzleHttp\Psr7\stream_for($data);
$this->assertSame(strlen($data), $stream->getSize());
$this->assertSame($data, $stream->read(strlen($data) + 1));
$this->assertSame(strlen($data), $stream->tell());
$this->assertTrue($stream->eof());
```

A workaround may be possible by comparing `tell()` with `size()` on affected versions, but it would lead to ugly quirks...

What do you think?

**Comment by sagikazarmark** [comment]
As of Guzzle PSR-7 2.0.0 the minimum required PHP version will be PHP 7.2 which doesn't have this issue. For now, I would suggest migrating to the latest PHP version as a solution.

**Comment by GrahamCampbell** [comment]
Closing, since this is a PHP bug present in only EOL PHP versions.
