### ISSUE TITLE
Function GuzzleHttp\Psr7\parse_request($message) doesn't support absolute URI's.

### ISSUE THREAD

**Issue by poison** [guzzle/psr7#24]
I was wondering why parse_request doesn't support absolute URI's. Request like this fail:

    GET https://www.google.com HTTP/1.1

The regex explicity requires a starting slash after the keyword:

    if (!preg_match('/^[a-zA-Z]+\s+\/.*/', $data['start-line'])) {
        throw new \InvalidArgumentException('Invalid request string');
    }

Are there any objections to support absolute URI's as well? I'm trying to build a php proxy server using reactphp/http (which uses guzzle/psr7) and it doesn't work because of this. If no objections I can create a PR.

Best,
Nicolas

**Comment by mtdowling** [comment]
Sounds fine to me.

**Comment by poison** [comment]
Were you able to check my PR #25 ? Any comments on it ?

Best,
Nicolas

**Comment by mtdowling** [comment]
PR #25 looks good, but I added a question to it: https://github.com/guzzle/psr7/pull/25#discussion_r35017764
