### ISSUE TITLE
Move all stream classes to Stream namespace

### ISSUE THREAD

**Issue by Nyholm** [guzzle/psr7#241]
Over half the classes in src is related to streams. However, this is a BC break we might not want to do. 

Ie, `src/Stream`

**Comment by sagikazarmark** [comment]
I don't know, I think it's kinda simple to have everything in the PSR7 namespace.

**Comment by Nyholm** [comment]
It is no real gain but it looks more organized. 

<img width="956" alt="screenshot 2018-12-09 at 12 48 03" src="https://user-images.githubusercontent.com/1275206/49696862-b9833600-fbb0-11e8-8ff1-dc91defd2853.png">

**Comment by sagikazarmark** [comment]
If this was a package like php-http/message with more parts I would be more inclined to support this proposal. But it's all about PSR-7 and PSR-17, so IMHO it isn't worth the confusion and effort caused by this change.

**Comment by Tobion** [comment]
I agree it would be nicer to add subnamespaces, but the bc break might be not worth it.
