### ISSUE TITLE
Improve PSR-7 integration test coverage

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/psr7#249]
https://travis-ci.org/php-http/psr7-integration-tests/jobs/462636552

**Comment by Nyholm** [comment]
:+1:

**Comment by Tobion** [comment]
requires https://github.com/php-http/psr7-integration-tests/pull/40

**Comment by Tobion** [comment]
And https://github.com/php-http/psr7-integration-tests/pull/10#issuecomment-499710500

**Comment by Tobion** [comment]
Tests should pass with the next patch release.
