### ISSUE TITLE
Support ralouphie/getallheaders:^3.0 too

### ISSUE THREAD

**Issue by willemstuursma** [guzzle/psr7#251]
A new version of [ralouphie/getallheaders](https://github.com/ralouphie/getallheaders) was released.

Its main advantage is that it does not ship any tests or CI files. Would be great if this version could also be allowed as a dependency.

**Comment by sagikazarmark** [comment]
It's already on master: #244 will be released as 1.6.0, but very likely only next year. In the meantime, you can use version override to install 3.0 if you want.

**Comment by willemstuursma** [comment]
Oh sorry, my bad! Thanks so much.
