### ISSUE TITLE
`Uri::withUserInfo` method should URL-encode the arguments

### ISSUE THREAD

**Issue by cedx** [guzzle/psr7#252]
_This aspect is not covered the PSR-7 spec (i.e. whether an implementation should URL-encode the "user info" component)._

When I use a `userInfo` containing special characters, I expect that the `Uri::withUserInfo` method produces a valid URI. That's not the case:

```php
use GuzzleHttp\Psr7\Uri;

$uri = (new Uri('http://domain.com'))->withUserInfo('foo@bar.com', 'pass#word');
echo (string) $uri;

// Actual:    http://foo@bar.com:pass#word@domain.com
// Expected:  http://foo%40bar.com:pass%23word@domain.com
```

If I want to have a valid URI, I must call `rawurlencode` on the arguments:

```php
$uri = (new Uri('http://domain.com'))
    ->withUserInfo(rawurlencode('foo@bar.com'), rawurlencode('pass#word'));
```

I think the URL-encoding should be handled by the `Uri::withUserInfo` method, not the library consumer.

**Comment by Tobion** [comment]
I agree the userinfo should get escaped. This is done for the other uri components as well and it's also how other libraries https://golang.org/pkg/net/url behave.
