### ISSUE TITLE
Invalid behaviour when using `stream_for` on `SplFileObject` resource.

### ISSUE THREAD

**Issue by shulard** [guzzle/psr7#256]
Hello !

I'm not sure it's a bug or not but I got a problem when I try to use a `SplFileObject` which represent an open file resource with the `stream_for` function. This "problem" is relevant when I use HTTPlug with the `GuzzleStreamFactory`.

That function contains a switch which choose to return a specific stream type based on the input data.

Here some examples :

```php
$handle = fopen($mypath, 'r');
\GuzzleHttp\Psr7\stream_for($handle); //Returns GuzzleHttp\Psr7\Stream

$handle = new \SplFileObject($mypath, 'r');
\GuzzleHttp\Psr7\stream_for($handle); //Returns GuzzleHttp\Psr7\PumpStream
```

`PumpStream` is returned because the SplFileObject is considered as an `object` and not as a `resource`. The problem for me is that a `PumpStream` can't return the stream size by design because it's a read wrapper around another kind of stream.

But, when using HTTPlug with CurlClient and trying to upload some file, the size is important because, based on that size, some logic is executed. For example, curl is asked to stop uploading the streamed file when the size is reached.

Is this behaviour an intended one ? Do you think that considering `SplFileObject` not as an interator but as a Stream can be useful ?

**Comment by Tobion** [comment]
It seems it's not possible to get the underlying resource of an SplFileObject https://www.php.net/manual/en/class.splfileobject.php 
So we can't just create a new stream with the underlying resource.

What we could do is create a new class StreamInterface implementation (SplFileObjectStream) that decorates SplFileObject and forwards all the calls. In `stream_for` we just handle create this new class.

**Comment by Tobion** [comment]
@shulard Do you want to work on this issue? Or create a failing test case?

**Comment by shulard** [comment]
Hello @Tobion !

I'll try to work on this issue asap, adding that `SplFileObjectStream` seems interesting ^^
