### ISSUE TITLE
GuzzleHttp\Psr7\Response Abstract Error

### ISSUE THREAD

**Issue by danhanly** [guzzle/psr7#26]
I'm getting the below message when interacting with Guzzle:

```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                  
  Class GuzzleHttp\Psr7\Response contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\ResponseInterface::setPostField)
```

**Comment by danhanly** [comment]
Strangely, my local version of psr/http-message::ResponseInterface had the 'setPostField' method, where the repo's version does not. I cannot track that method down for the life of me.

**Comment by mtdowling** [comment]
`Psr\Http\Message\ResponseInterface::setPostField` is not even on that interface: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md#33-psrhttpmessageresponseinterface. This seems like a weird environment specific issue.
