### ISSUE TITLE
Build fail on HHVM 4.0

### ISSUE THREAD

**Issue by Bu4ak** [guzzle/psr7#260]
After I created the PR ( https://github.com/guzzle/psr7/pull/259 ), I saw that the build ended with an error ( https://travis-ci.org/guzzle/psr7/jobs/492774182 ). 
And on master too https://travis-ci.org/Bu4ak/psr7/jobs/493026322 .

I think it happened because of the hhvm updated two days ago  ( https://github.com/facebook/hhvm/releases/tag/HHVM-4.0.0 )

And Travis uses it (4.0.0) instead of the previous one (3.30.3), because the version in the config is not specified.

**Comment by Bu4ak** [comment]
https://github.com/composer/composer/issues/7990

We need to specify the version or delete the step hhvm

**Comment by sagikazarmark** [comment]
Thanks @Bu4ak . We are aiming to drop HHVM support, so #262 should fix the problem.
