### ISSUE TITLE
withHost() implementation does not respect UriInterface

### ISSUE THREAD

**Issue by mxr576** [guzzle/psr7#261]
According to PSR-7 UriInterface definition if an empty string passed to `withHost()` it should clear the host. The current implementation in this library automatically falls back to "localhost" in this case.

Expected:
https://github.com/php-fig/http-message/blob/master/src/UriInterface.php#L215
https://github.com/php-fig/http-message/blob/master/src/UriInterface.php#L82

Actual:
https://github.com/guzzle/psr7/blob/master/src/Uri.php#L456
https://github.com/guzzle/psr7/blob/master/src/Uri.php#L739

Using an empty space as a parameter is not a real solution for this problem, because it causes problems, for example with the string representation of the URI.

**Comment by mxr576** [comment]
Background story:
I tried to remove authority information from the logs that my library generates by using the [SimpleFormatter](https://github.com/php-http/message/blob/1.7.2/src/Formatter/SimpleFormatter.php#L25) plugin (provided by HTTPlug) by running `$request = $request->withUri($request->getUri()->withHost('')->withPort(null)->withUserInfo('', ''));` before a log entry gets generated.

(The [FullHTMLFormatter](https://github.com/php-http/message/blob/1.7.2/src/Formatter/FullHttpMessageFormatter.php#L39) plugin does not have this problem, I am aware of that, but my library allows to select the logger plugin and SimpleFormatter is one of the options.)

**Comment by Nyholm** [comment]
You are correct. This is an issue.

**Comment by sagikazarmark** [comment]
@mxr576 are you willing to provide a PR?

**Comment by mxr576** [comment]
Now that it is confirmed, I'll try to provide one until the end of this week.

**Comment by sagikazarmark** [comment]
Thanks!

**Comment by Tobion** [comment]
Http(s) schemes require a host. The `localhost` default is only there to be a little more fault-tolerant. The alternative would be to throw an exception. All you need to do is removing the scheme before removing the host, e.g. `$request->getUri()->withScheme('')->withHost('')->withPort(null)->withUserInfo('', '');`.
