### ISSUE TITLE
Boolean representation on GuzzleHttp\Psr7\build_query()

### ISSUE THREAD

**Issue by ackintosh** [guzzle/psr7#264]
```php
$data = [
    'true' => true,
    'false' => false
];

/*
 * GuzzleHttp\Psr7\build_query()
 */
var_dump(GuzzleHttp\Psr7\build_query($data));
// string(13) "true=1&false="

/*
 * \http_build_query()
 */
var_dump(\http_build_query($data));
// string(14) "true=1&false=0"
```

`GuzzleHttp\Psr7\build_query()` resolves `false` to `''` but I think it should be `0` as well as `\http_build_query()`.

I'll file a PR if it's reasonable for you too.

**Comment by pierrre** [comment]
FYI this code is called by swagger-codegen.
All code generated by swagger-codegen is broken currently.
