### ISSUE TITLE
Allow __toString to throw exception with PHP 7.4

### ISSUE THREAD

**Issue by Tobion** [guzzle/psr7#271]
Due to https://wiki.php.net/rfc/tostring_exceptions we should throw the underlying exception in __toString methods again when using PHP >= 7.4
This might also be a topic for a PSR-7 errata because of the outdated information in https://www.php-fig.org/psr/psr-7/

> This method MUST NOT raise an exception in order to conform with PHP's string casting operations.

Ref. #243

**Comment by Nyholm** [comment]
I would say no because the PSR specification says no. 

If the PSR had defined a `toString()` instead if `__toString` then it would be clear that we cannot allow it to throw exceptions.

**Comment by Tobion** [comment]
The PSR specification only says so because of the PHP limitation. Throwing an exception instead will only make things easier to debug as it gives a real stack trace. There are no disadvantages.

**Comment by Nyholm** [comment]
The disadvantage is that we don’t follow the specification. 

I agree that the reasoning behind the specification might be flawed. But I don’t think we should go against it.

**Comment by Tobion** [comment]
It does not matter what the specification says when it does not have an impact on users. An exception or an unusable toString with a trigger error has the same outcome: it does not work.

**Comment by Nyholm** [comment]
Can you elaborate what you mean when you say it does not have an impact on the users. 
I believe it has an impact, but I might be misinformed.

**Comment by GrahamCampbell** [comment]
Maybe there should be an errata added to the spec, to clarify if it's now OK to throw exceptions on PHP 7.4+, or if it still must not, under any circumstances?

**Comment by Tobion** [comment]
Feel free to try. I asked and submitted psr erratas several times. No progress was ever made.

**Comment by Tobion** [comment]
> Can you elaborate what you mean when you say it does not have an impact on the users.

It's an error condition that should not happen. And if it does, you likely didn't explicitly handle this case. And even if you do, the only difference is if you use try catch (like in all other psr-7 methods that throw exceptions) or an error handler.
