### ISSUE TITLE
Integer value in headers

### ISSUE THREAD

**Issue by hutnikau** [guzzle/psr7#273]
When `\GuzzleHttp\PrepareBodyMiddleware` modifies headers it calls
`$request->getBody()->getSize()` to set `Content-Length` header, and the type of of that value is `integer` : https://github.com/guzzle/guzzle/blob/master/src/PrepareBodyMiddleware.php#L55

Thus this change always leads to `Header value must be a string or an array of strings.` exception:
https://github.com/guzzle/psr7/pull/250/files#diff-5abca4d9d5693da46d10a54795b1192dR157

**Comment by Tobion** [comment]
#272 allows numeric values again
