### ISSUE TITLE
Next 1.x release

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/psr7#278]
Thanks for the great work on this package. Is another release planned soon? Are there any outstanding issues I could help with in 1.x?

**Comment by sagikazarmark** [comment]
We are long due with a new 1.x release. Thanks to @Tobion most of the open issues/PRs has been closed, so I think we are very close to a 1.6 version.

I also plan it to be the last 1.x version.

I'll go through the remaining issues and PRs to see if something needs immediate attention.

**Comment by GrahamCampbell** [comment]
🚀

**Comment by hngl** [comment]
The requirement of ` "ralouphie/getallheaders": "^2.0.5"` in release 1.5.2 is outdated. Now the _Wordpress Plugin Directory_ rejects our plugin. This is already fixed in `master` ( `"ralouphie/getallheaders": "^2.0.5 || ^3.0.0"`), yet not available from composer.

@Tobion Please release. How can I help?

**Comment by sagikazarmark** [comment]
@hngl you can force installing a 3.x version:

```json
"ralouphie/getallheaders": "^3.0 as 2.0.5"
```

This will satisfy the version constraint until a new version is released.

**Comment by hngl** [comment]
Thanks @sagikazarmark, that unblocked my issue!

**Comment by dvdknaap** [comment]
For the one that want to fix this with @sagikazarmark his suggestion, you can't use an ^ in the version but only an specific version, just change it to the latest version

```"ralouphie/getallheaders": "3.0.3 as 2.0.5"```

**Comment by sagikazarmark** [comment]
Ah, good catch @dvdknaap , thanks!

**Comment by Tobion** [comment]
I released 1.6.0, have a great weekend.

**Comment by GrahamCampbell** [comment]
🍻
