### ISSUE TITLE
How hard would it be to add support of PHP 5.3?

### ISSUE THREAD

**Issue by kirill-konshin** [guzzle/psr7#28]
I know that it's super obsolete, but some of our customers still use it...

It would be great if Guzzle PSR-7 implementation will also be 5.3 compatible.

**Comment by mtdowling** [comment]
I don't think it's a good idea to downgrade to 5.3 at this point. It would require additional dev time to ensure 5.3 compatibility, and that's something that most of the PHP community is moving away from supporting. Maybe you can create a 5.3 compatible fork.

**Comment by kirill-konshin** [comment]
What if I will create a PR instead?

So far I can see that `[]` are used instead of `array()` and traits. Traits can be replaced with base classes since all classes that use traits do not extend anything and only implement the interface.

**Comment by mtdowling** [comment]
It's not a one time cost. It's also maintenance going forward.

**Comment by kirill-konshin** [comment]
Do you have anything special in the roadmap for this project?

**Comment by kirill-konshin** [comment]
Will you accept a PR or should I just make a fork?

**Comment by mtdowling** [comment]
You should fork if you need PHP 5.3 support. Apologies, but I don't want to support 5.3 in this repo.

**Comment by kirill-konshin** [comment]
Since in our company we have a requirement to support 5.3 and Guzzle\PSR7 will be used in company PHP SDK I think I can support 5.3 on long term. I will fork the repo then make a PR, but it's up to you to accept it.

**Comment by kirill-konshin** [comment]
Made a PR https://github.com/guzzle/psr7/pull/30
