### ISSUE TITLE
[BC Break] Request::__construct `assertMethod` in 1.6.1

### ISSUE THREAD

**Issue by alex2005git** [guzzle/psr7#288]
Today I've updated to v1.6.1 from v1.5.2, and I got errors because of `assertMethod`  

I was using it as follows `new Request('', '')`, and now it throws an exception `Method must be a non-empty string.`

**Comment by alex2005git** [comment]
Line in question https://github.com/guzzle/psr7/blame/master/src/Request.php#L42

**Comment by sagikazarmark** [comment]
Technically creating a request without a method is invalid, that's why we fixed this. Although it is a BC break, it is a fix so unless it has a large effect on the community (eg. it's not trivial to fix, several other components are affected) it should remain in the 1.6.x release branch.

**Comment by thewilkybarkid** [comment]
Related, objects that can cast to strings are now rejected (refs https://github.com/elifesciences/api-sdk-php/pull/195/commits/2e2f68266714071cfd6ccc018a899e21705d14b8).

**Comment by GrahamCampbell** [comment]
I don't think this is a BC break. The caller code didn't satisfy the callee precondition, so the behaviour was undefined and not covered by semver.

That is, to say, the function expected a string, and you didn't pass one. Anything could happen. ;)

**Comment by alex2005git** [comment]
> I don't think this is a BC break. The caller code didn't satisfy the callee precondition, so the behaviour was undefined and not covered by semver.

The callee precondition changed after the fact though, before it was acceptable to pass an empty string.
> 
> That is, to say, the function expected a string, and you didn't pass one. Anything could happen. ;)

`''` is a valid string, so I was in fact passing it a string (an empty one, but still a string).  

Highly disagreed, because the library had a bug in it (not checking for empty strings), doesn't mean that my application should break when updating the minor version. The correct way would be to display a deprecation notice on an empty string, and throw an error when incrementing the major version.  
Let's quote semver https://semver.org/#spec-item-8
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

So you still not agree that by throwing an error in a minor version update, when before it didn't, that it is a BC break?

**Comment by GrahamCampbell** [comment]
> The callee precondition changed after the fact though, before it was acceptable to pass an empty string.

The precondition was always "only pass a string". It was just never enforced by the code.

**Comment by GrahamCampbell** [comment]
Preconditions need not be enforced in general, as is common in lots of dynamic code, in general, and in particular, older PHP code. You can think of the specification, which has the preconditions, as separate from the code, and never changing. An implementation must do what the specification says on things that satisfy the precondition, but behaviour is undefined otherwise.

**Comment by GrahamCampbell** [comment]
Increasingly, as PHP's internals have become faster, people are wanting to enforce more of the non-code preconditions, such as adding scalar typing in the code. This was always possible with assert statements or otherwise, it just wasn't popular.

**Comment by Tobion** [comment]
Closing. Any such change can be a bc break if you craft certain conditions. An empty method is not allowed according to HTTP standards. So it's not a valid value. Also I don't think it's hard to change '' to 'GET' or whatever you intend to do in your code.

**Comment by Tobion** [comment]
We are adding certain validations to fix security and bugs, see for example https://github.com/guzzle/psr7/pull/307
