### ISSUE TITLE
PR #253 introduces a regression in 1.6

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/psr7#290]
Looks like this is another unfortunate regression caused by #253. 😞 

Details:

https://travis-ci.org/guzzle/guzzle/jobs/558517697#L599

https://github.com/guzzle/guzzle/blob/2297b43/src/RedirectMiddleware.php#L189

**Comment by gmponos** [comment]
I think i have a PR about it...

https://github.com/guzzle/psr7/pull/284

Isn't this a fix for it?

**Comment by gmponos** [comment]
I guess we can close this...
