### ISSUE TITLE
Headers with multiple values should only be separated by a comma

### ISSUE THREAD

**Issue by adriansuter** [guzzle/psr7#300]
Hi all

The PSR7-specification (see PR https://github.com/php-fig/fig-standards/pull/1194) as well as the RFC 2616 define a comma, not comma with white-space, as separator.

We should probably update the following method:
https://github.com/guzzle/psr7/blob/152fab1581e564743e14a85adb33c01e8773b254/src/MessageTrait.php#L65-L68

**Comment by adriansuter** [comment]
See https://github.com/Nyholm/psr7/issues/137 for further opinions and discussions.

**Comment by Tobion** [comment]
Closing as per https://github.com/Nyholm/psr7/issues/137#issuecomment-629275400
