### ISSUE TITLE
"Invalid request string" error when parse_request with relative URL

### ISSUE THREAD

**Issue by phanan** [guzzle/psr7#306]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

Steps to reproduce:

1. Create a new `Request` object with a relative URL: `$request = new Request('get', '/users')`
1. Convert the object into its string representation: `$rep = str($request)`
1. Convert the string back to the object using `parse_request`: `$restored = parse_request($rep)`

#### Actual Behavior

An "Invalid request string" error thrown, apparently because of the `preg_match` check in `parse_request()`:

```php
    if (!preg_match('/^[\S]+\s+([a-zA-Z]+:\/\/|\/).*/', $data['start-line'], $matches)) {
        throw new \InvalidArgumentException('Invalid request string');
    }
```

#### Expected Behavior

The `parse_request` parses and returns the request object successfully.

**Comment by GrahamCampbell** [comment]
Are relative rules intended to be supported by that method?
