### ISSUE TITLE
Fetching headers with getallheaders() only works with apache

### ISSUE THREAD

**Issue by lackovic10** [guzzle/psr7#312]
**Description**
[ServerRequest::fromGlobals()](https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php#L173) uses the `getallheaders()` to get the headers, but that function only works with apache

**Possible Solution**
I have submitted a pull request [ServerRequest::fromGlobals() - fix the fetching of request headers](https://github.com/guzzle/psr7/pull/147) more than two and a half years ago which got declined, but i see nothing related has been done since
Is there any ongoing initiative or maybe my pull request can be accepted after all?

**Comment by lackovic10** [comment]
@sagikazarmark @Tobion

**Comment by Tobion** [comment]
Does #162 not fix it? A simple search or looking at the references should have shown that PR.

**Comment by lackovic10** [comment]
sorry, i forgot to close this, a colleague pointed that you are not using the native `getallheaders()` and it looks like it woks fine with nginx as well
