### ISSUE TITLE
move public functions to abstract class

### ISSUE THREAD

**Issue by TheKito** [guzzle/psr7#325]
**Description**
Move all public functions in functions.php to static functions in Functions class to get more friendly with php object oriented style and keep but decrapted functions_include.php with proxy functions for backward compatibility with other projects

**Example**
For example Psr7\stream_for changes to Psr7\Functions::stream_for

**Additional context**

namespace GuzzleHttp\Psr7;

use Psr\Http\Message\MessageInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\StreamInterface;
use Psr\Http\Message\UriInterface;

abstract class Functions
{

    public static function stream_for($resource = '', array $options = [])
    {
        if (is_scalar($resource)) {
            $stream = fopen('php://temp', 'r+');
            if ($resource !== '') {
                fwrite($stream, $resource);
                fseek($stream, 0);
            }
            return new Stream($stream, $options);
        }
.....

**Comment by GrahamCampbell** [comment]
This has already been considered, and I have implemented it: https://github.com/guzzle/psr7/pull/308.

**Comment by TheKito** [comment]
Great, if i can collaborate please do not hesitate to contact me thanks.
