### ISSUE TITLE
MessageTrait::$stream isn't always set/initialized (psalm)

### ISSUE THREAD

**Issue by mkuettel** [guzzle/psr7#326]
**PHP version**: 7.4.2 (hint: `php --version`)
**Psalm version**: 3.9.3

**Description**
In our codebase we use psalm to statically analyze the source code.
We have our own class extend the `\GuzzleHttp\Psr7\ServerRequest` class.
When the `PropertyNotSetInConstructor` check is active, the following error is reported:

```
ERROR: PropertyNotSetInConstructor - lib/my-http-request.php:1:1- Property MyHttpRequest::$stream is not defined in constructor of MyHttpRequest and in any methods called in the constructor
class PsRequest extends \GuzzleHttp\Psr7\ServerRequest
```

Because MessageTrait::$stream is private I cannot Initialize it in my constructor either (and probably shouldn't anyway).

I can of course suppress this instance of the check, but then I won't notice when I don't initialize a property of this class.

**How to reproduce**

In your `psalm.xml` you need `<PropertyNotSetInConstructor errorLevel="error" />`

_lib/my-http-request.php_:
```
<?php

class MyHttpRequest extends \GuzzleHttp\Psr7\ServerRequest {
}
```

**Possible Solution**

It's about this property here in the `MessageTrait`:
https://github.com/guzzle/psr7/blob/master/src/MessageTrait.php#L24

In the `Request` class the `$stream` property only gets conditionally initialized. It should probably be initialized either way.
https://github.com/guzzle/psr7/blob/master/src/Request.php#L57

**Additional context**

**Comment by Tobion** [comment]
$stream is not initialized on purpose when the body is empty as a performance optimization.
I've fixed the declaration to
```
/** @var StreamInterface|null */
private $stream;
```
in #333 which should also fix the psalm report.

**Comment by Tobion** [comment]
Also fixed in 1.x
