### ISSUE TITLE
PSR-17 stable release

### ISSUE THREAD

**Issue by enumag** [guzzle/psr7#327]
In composer.json this library claims to provide `psr/http-factory-implementation`. However this is only true for the master branch and the implementation isn't available in any stable release.

Do you have any ETA when a stable PSR-17 implementation might be available? If not can you recommend me some other library which I could use in the meantime?

**Comment by baukevdw** [comment]
In the meantime you could use https://github.com/http-interop/http-factory-guzzle

**Comment by barryvdh** [comment]
I'm also interested in this. We're in the process of upgrading the Omnipay package to use guzzle/psr7 without additional adapters, but not sure on the timeframe for v2. Are there any blockers or issues we can help/test with?

**Comment by sagikazarmark** [comment]
I think we are pretty close to version two, at least I don't see any more major changes. There are two outstanding items in the 2.0 milestone at the moment. We should probably review things and finalize the v2 milestone and set a date for the release.

/cc @Tobion @Nyholm WDYT?

**Comment by GrahamCampbell** [comment]
A 1.x -> 2.x merge is also needed. That will be a **major** job.

**Comment by barryvdh** [comment]
That would be mostly applying your PR (https://github.com/guzzle/psr7/pull/345) to the master branch right?

**Comment by GrahamCampbell** [comment]
Yeh. That's no small thing, though. ;)

**Comment by andypost** [comment]
Any schedule for release?
 this issue a blocker to declare Drupal 9.1 compatible with PHP 8

**Comment by bbrala** [comment]
I've made a PR with the 1.x merge, i'll double check test results tonight. :)

**Comment by bbrala** [comment]
Seems i need to check a few things still. (like codestyle)

**Comment by bbrala** [comment]
Well, all tests are green, codestyle if good, but there is some errors left in phpstan. I could nagate those errors with some extra checks, but not sure if i should. @GrahamCampbell  what do you think?

```
 ------ -----------------------------------------------------------------------------------
  Line   Message.php
 ------ -----------------------------------------------------------------------------------
  148    Variable $headerLines in PHPDoc tag @var does not match assigned variable $count.
 ------ -----------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Utils.php
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------
  301    Parameter #1 $fp of function fwrite expects resource, resource|false given.
  301    Parameter #2 $str of function fwrite expects string, bool|float|int|string given.
  302    Parameter #1 $fp of function fseek expects resource, resource|false given.
  304    Parameter #1 $stream of class GuzzleHttp\Psr7\Stream constructor expects resource, resource|false given.
  309    Parameter #1 $stream of class GuzzleHttp\Psr7\Stream constructor expects resource, (callable)|Iterator|Psr\Http\Message\StreamInterface|resource|null given.
  322    Parameter #1 $object of function method_exists expects object|string, (callable)|resource|null given.
  327    Parameter #1 $stream of class GuzzleHttp\Psr7\Stream constructor expects resource, resource|false given.
  353    Parameter #1 $callback of function set_error_handler expects (callable(int, string, string, int, array): bool)|null, Closure(): void given.
  370    Method GuzzleHttp\Psr7\Utils::tryFopen() should return resource but returns resource|false.
  396    Unreachable statement - code above always terminates.
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by bbrala** [comment]
There, i've fixed the last phpstan errors, either by some extra checks or adding an ignore to lines where phpstan doesn't completely understand the code. Everything is green in #360

**Comment by bbrala** [comment]
The PR is open for a little bit now, i did make the appropiate changes as asked by @Tobion. Hopefully it can be reviewed again soon.

**Comment by lex0r** [comment]
HttpFactory.php is not included in 1.7.0 while Okta's documentation says you "can just include guzzle/psr7" (https://developer.okta.com/docs/guides/protect-your-api/php/configure-packages/) without dev-master...

**Comment by bretterer** [comment]
Brian from Okta.  This is a pretty large issue for us now. We would like to assist in any way we can to get a release out with this update. What can we do to help with this?

**Comment by bbrala** [comment]
@bretterer You could review PR #360 perhaps, that could help getting it merged sooner rather than later.

**Comment by xjm** [comment]
So now PR #360 was closed on account of the PR being too much review and not done by contributors who were already known to the maintainers. Myself and @andypost were following #360 because as far as we understood it was the only way we could help contribute to PSR-17 becoming available in a stable release (which is important for us in Drupal).

If that's not it, what's the next step?

**Comment by Nyholm** [comment]
Here is a small status update: 

PSR17 is a feature of 2.0. You will find the milestone here: https://github.com/guzzle/psr7/milestone/2

@GrahamCampbell is spending a lot of time making sure 2.0 is ready. I am helping and will increase my efforts the next few days. 

The plan: 
1. Make sure the milestone is empty
2. Test the master branch
3. Release an alpha and then a beta release for 2.0
4. When everything seams fine, we tag 2.0.

If you want to help: 
1. Review the new PRs and test them. Write comments!
2. Test dev-master in your projects to make sure it is working
3. Open github issues and report errors. 
4. Create small PRs to open issues in the milestone. 
5. Use the Githubs Sponsor feature

**Comment by bretterer** [comment]
@Nyholm Thanks for the update on this.

I will spend some time next week reviewing the PR to give feedback and track down any issues that I can see.

**Comment by GrahamCampbell** [comment]
2.0.0 beta release will be happening very soon. :)

**Comment by bbrala** [comment]
Thanks for getting work done @GrahamCampbell and @Nyholm :)

**Comment by Nyholm** [comment]
2.0.0-beta 1 is released now!

**Comment by xjm** [comment]
Great news! We will start testing it. Thanks so much!
