### ISSUE TITLE
Add http status code 308 (Permanent Redirect)

### ISSUE THREAD

**Issue by onyn** [guzzle/psr7#341]
Noticed that [Response.php](https://github.com/guzzle/psr7/blob/master/src/Response.php) missing http status code 308 (Permanent Redirect) that was introduced in [RFC7538](https://tools.ietf.org/html/rfc7538).

**Comment by GrahamCampbell** [comment]
That's because that standard hasn't been accepted?

**Comment by GrahamCampbell** [comment]
![image](https://user-images.githubusercontent.com/2829600/83053667-024ed900-a049-11ea-93e0-7833568ab282.png)

**Comment by onyn** [comment]
511, 451, 431, 429, 428 are also hasn't been accepted.
And 510 is not just "proposed", but even "experimental".
Not to mention the 418, which is not even a standard.

**Comment by GrahamCampbell** [comment]
Fair enough. ;)
