### ISSUE TITLE
How can I add some helper methods to ServerRequest class if extending this class is limited?

### ISSUE THREAD

**Issue by evonicgu** [guzzle/psr7#348]
I want to add some useful methods like validating some parameters and other stuff to ServerRequest class, but as it has `fromGlobals()` method, which doesn't use late static binding I cannot do it. Are there any other possibilities to add extra functionality without using functions in global scope or namespaced functions?

**Comment by GrahamCampbell** [comment]
You wouldn't add helper methods. You could have a function which takes as input the server request, and as output does what you need. Adding helpers by class extension is a violation of SOLID.

**Comment by GrahamCampbell** [comment]
That class is not going to be marked as final, anyway, so you can extend it if you really want. ;)
