### ISSUE TITLE
Make more classes final

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/psr7#352]
#286 got closed, but I think we can make a couple more classes final. Since this package implements the PSR-7 standard, I think those implementations should also be final.

**Comment by GrahamCampbell** [comment]
We should add phpdoc final annotations in the 1.x series marking the classes we intend to make final in 2.x (just like guzzle 7 has done before guzzle 8).

**Comment by xjm** [comment]
@sagikazarmark Do you mean making `Request` and `Response` final?

I'd question whether that is actually desirable. Other PSR-7 implementations do extend their `RequestInterface` or `ResponseInterface` implementations for specific purposes. E.g., Diactoros adds many response type subclasses to its `ResponseInterface` implementations.

**Comment by GrahamCampbell** [comment]
The argument to making classes final where there is an interface available is that if you want to add to their functionality, you can do this by implementing the interface yourself and wrapping an instance of the original, instead of using extension. This usually leads to code that is less buggy, since you have no mechanism for messing with the internals of the class you would otherwise be extending. All you have is its public interface.

**Comment by xjm** [comment]
@GrahamCampbell I agree that that is a point of view. However, there are downsides -- code duplication, bugs being fixed in one copy of the implementation but not another, etc. "Messing with internals" can also be phrased as "Making use of provided public API".

**Comment by sagikazarmark** [comment]
> I guess It comes down to whether you want to not consider the PSR-7 implementation itself API

Exactly! We don't. :) Primarily because then we have to maintain those APIs as well (keep them backward compatible).

People often requested that we opened those APIs, but we always turned down those requests, because...well, they are internal and we don't want to maintain them. Making all classes final will put an end to that discussion.

There is an argument, that extending PSR-7 messages (classes) is bad design and we don't want to support that (which is probably true), but ultimately the purpose of this library is to be used with Guzzle.

At the same time, it implements the PSR-7 contract (hopefully we'll soon release the PSR-17 support as well), so it should be interoperable with other libraries.

TBH, I often wonder if we should just abandon this library, move everything back to the Guzzle repo and make everything internal. It would certainly make the development of Guzzle easier.

**Comment by GrahamCampbell** [comment]
We already have some final classes in master. Those are unlikely to be reverted. This issue exists to discuss what else we might want to make final.

**Comment by xjm** [comment]
I'm not objecting to _all_ use of final, just making sure you want to do this rather late in the release process to existing APIs that would commonly have been used as extension points (they are even described as sucg in the initial comment on #336).

**Comment by GrahamCampbell** [comment]
We have made no BC promise on the state of the master branch yet, and there absolutely will be more breaking changes this week.

**Comment by xjm** [comment]
Of course the development branch has no BC promise -- I was referring to the impact on folks using Guzzle 6 or 7 who will inevitably need to update to this, and the extent to which it's desirable to force those to be rearchitected and also release new major versions. I guess it also raises the question of how long 1.x will be supported.

**Comment by GrahamCampbell** [comment]
Guzzle 7 will likely support both v1 and v2 of this package. I don't see any reason to force people onto v2 so soon.

**Comment by GrahamCampbell** [comment]
Guzzle 6 is EOL and will not be compatible with v2 of this package.

**Comment by GrahamCampbell** [comment]
I've reviewed which classes are final. I am happy with the list that was chosen.

**Comment by GrahamCampbell** [comment]
1.8.0 will be released before or with 2.0.0, and soft-final marks all classes that exist in 1.x that are final in 2.x.
