### ISSUE TITLE
Exception: rawurlencode() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by 4n70w4** [guzzle/psr7#358]
**PHP version**: 7.4.9 (hint: `php --version`)

**Description**

Can't use `\GuzzleHttp\Psr7\build_query` for multidemensional arrays.

But `http_build_query` from PHP core works without errors.

**How to reproduce**

```php
        $queryParams = [
            'session' => 'demo',
            'settings' => [
                'settings' => [
                    'app_info' => [
                        'app_id' => 123,
                        'app_hash' => '321',
                    ],
                ],
            ],
        ];

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
```

**Possible Solution**

May be use recursive function if `$vv` is array too

https://github.com/guzzle/psr7/blob/7858757f390bbe4b3d81762a97d6e6e786bb70ad/src/functions.php#L591

**Additional context**

**Comment by Nyholm** [comment]
Consider this code. 

```php
$data = [
    'foo' => ['v1', 'v2'],
];

echo \GuzzleHttp\Psr7\build_query($data); 
// foo=v1&foo=v2

echo http_build_query($data); 
// foo%5B0%5D=v1&foo%5B1%5D=v2

echo urldecode(http_build_query($data)); 
// foo[0]=v1&foo[1]=v2
```

In your example, how would the final query sting look?

**Comment by GrahamCampbell** [comment]
Ping @4n70w4.

**Comment by ybelenko** [comment]
> In your example, how would the final query sting look?

My guess is `session=demo&settings[settings][app_info][app_id]=123&settings[settings][app_info][app_hash]=321`

Btw, we're struggling with the same issue right now at [OpenAPI-Generator - PR 11225](https://github.com/OpenAPITools/openapi-generator/pull/11225). Trying to add `deepObject` serialization support with `GuzzleHttp\Psr7\Query::build` static helper.
