### ISSUE TITLE
CachingSteam returns incorrect stream size (call to `getSize`)

### ISSUE THREAD

**Issue by psdesse** [guzzle/psr7#365]
**PHP version**: 7.3.19

**Description**
`getSize` on `CachingSteam` does not handle cases when the remote steam does not know its size (ie, returns `null` on `getSize`). In this case, the size returned by the `CachingStream` is incorrect. It does a `max` between `null` and the cached size, which will always return the cached size even if the full stream was not cached.

**How to reproduce**
Create a `CachingStream` from a stream that does not know its size (returning `null` when calling `getSize`).

**Possible Solution**
As a first idea, I am wondering why the `getSize` on the `CachingStream` does not only returns the size advertised by the remote stream. However, we could improve this by knowing if the full stream has been cached. In this case, the size is known and it could returns.

**Additional context**
In the `seek` function, the case were the remote stream returns `null` on `getSize` is correctly handled.

**Comment by Nyholm** [comment]
>  I am wondering why the getSize on the CachingStream does not only returns the size advertised by the remote stream.

I think this makes sense too. 

I agree with your suggestion.

**Comment by GrahamCampbell** [comment]
Not stale.

**Comment by Nyholm** [comment]
Closed by #438
