### ISSUE TITLE
GuzzleHttp\Psr7\stream_for() 

### ISSUE THREAD

**Issue by MrGasper** [guzzle/psr7#367]
Hello,

I was reading the same error in other files, in this case I present it in the psr7/request.php file.

I had the same error in Handler/CurlFactory.php and updating was fixed.

If you can guide me, please thank you.

![image](https://user-images.githubusercontent.com/28965558/105833297-fda34180-5f96-11eb-90a7-cff1b0040f68.png)
![image](https://user-images.githubusercontent.com/28965558/105834197-2d9f1480-5f98-11eb-8fd7-9b8ed6f17921.png)

**Comment by GrahamCampbell** [comment]
You probably have the wrong version of this package installed. That code doesn't exist in the latest version: https://github.com/guzzle/psr7/blob/1.7.0/src/Request.php#L55.

**Comment by alanondra** [comment]
Yes, make sure your entire Guzzle dependency is updated. The `stream_for` function was moved to the `Utils` class:

https://docs.guzzlephp.org/en/stable/psr7.html#creating-streams
