### ISSUE TITLE
Stream::getContents() unexpected behavior

### ISSUE THREAD

**Issue by slavcodev** [guzzle/psr7#38]
Hello, I hit one problem when use instance of `GuzzleHttp\Psr7\Stream`.

```
echo $response->getBody()->getContents();
```

method returns me empty string, although the logger show me correct response.

The problem was that the logger use `(string) $response->getBody()` and we seek to the end of stream.

Should we seek back before returns content?

```php
public function getContents()
{
    $this->rewind();
    $contents = stream_get_contents($this->stream);

    if ($contents === false) {
        throw new \RuntimeException('Unable to read stream contents');
    }

    return $contents;
}
```

Seems `__toString()` can call `getContent()`.

**Comment by mtdowling** [comment]
If you need to seek and store the entire stream in memory then cast the stream to a string using (string)

**Comment by slavcodev** [comment]
Well, I think `getContents` meaning all body contents, not a part. To read body partial we have `read($length)`. Or I''m wrong?

**Comment by mtdowling** [comment]
See https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L143

**Comment by kenorb** [comment]
The `$response->getBody()` should be enough, however when calling it for the first time, you've to `rewind` it if you're planning to access content for the second time.

For example, I have called `$response->getBody()`, then when calling `getContents();`, the result was always empty. Doing `$response->rewind();` in this case helped.
