### ISSUE TITLE
Can't send file from stream_type MEMORY

### ISSUE THREAD

**Issue by bscheshirwork** [guzzle/psr7#411]
**PHP version**: 7.3.27 (hint: `php --version`)

**Description**
```
Undefined index: uri in /app/vendor/guzzlehttp/psr7/src/Utils.php:320
```

`\stream_get_meta_data($resource)` return
```
array (
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
  'stream_type' => 'MEMORY',
  'mode' => 'rb',
  'unread_bytes' => 0,
  'seekable' => true,
)
```

**How to reproduce**

1. read 0 bytes from `bytea` field of table with `ActiveRecord` `yii2` 
(as resource from \PDOStatement::execute(); \PDOStatement::fetch(); see https://www.php.net/manual/en/class.pdostatement.php )
2. send as multipart file this resource

**Possible Solution**

```
                $metaData = \stream_get_meta_data($resource);
                if (array_key_exists('uri', $metaData) && $metaData['uri'] === 'php://input') {
```
or
```
                if (\stream_get_meta_data($resource)['uri'] ?? '' === 'php://input') {
```
**Additional context**

**Comment by GrahamCampbell** [comment]
Fixed in 1.8.2 and 2.0.0.
