### ISSUE TITLE
Stream::getSize doesn't return 0 for streamed resources

### ISSUE THREAD

**Issue by martinsbalodis** [guzzle/psr7#421]
**PHP version**: 7.4.18

**Description**
`Stream::getSize` should return null for a file like `/dev/zero`  instead 0 is returned.

**How to reproduce**
```php
$fh = fopen('/dev/zero', 'r');
$stream = \GuzzleHttp\PSr7\Utils::streamFor($fh);
$size = $stream->getSize();
var_dump($size);
// 0
```

**Possible Solution**
Check `$stat['mode']` to figure out whether the resource is n stream with unknown size.

**Additional context**
In the `Stream::getSize` it seems that you have tried to handle this in a way where you would expect that the fstat function doesn't return `'size'. I tried to alter the data that is handed to fstat function. It seems that there is no way to have size not set in the result array. A situation like this shouldn't be possible:

```php
//                      !
if (is_array($stats) && !isset($stats['size'])) {
	...
}
```

**Comment by Nyholm** [comment]
According to the [PSR-7 specification](https://www.php-fig.org/psr/psr-7/): 

```php

    /**
     * Get the size of the stream if known.
     *
     * @return int|null Returns the size in bytes if known, or null if unknown.
     */
    public function getSize();
```

You discovered that we asked `fstat` about the size of the stream. Fstat reports size: 0, that is why we return it. 

Could you describe the scenario when this is causing issues for you?
