### ISSUE TITLE
Security email not working

### ISSUE THREAD

**Issue by 0xcrypto** [guzzle/psr7#423]
I have reported a issue through huntr.dev platform which might have tried contacting on the email security@guzzlephp.org. I have also tried to contact as well but the mailer daemon threw back an error email  "Diagnostic-Code: Host not reachable." Is the email active?

Meanwhile can you please take a look at https://www.huntr.dev/bounties/1-guzzle/psr7/

Thanks.

**Comment by GrahamCampbell** [comment]
Please email me directly at `hello at gjcampbell dot co dot uk`. We don't handle bounties via third party sites.

**Comment by 0xcrypto** [comment]
@GrahamCampbell emailed you.

**Comment by GrahamCampbell** [comment]
I haven't received anything. Did you get the email address right?

**Comment by 0xcrypto** [comment]
Rechecked, email is correct and mail delivery was successful. Maybe it went to spam folder?

**Comment by GrahamCampbell** [comment]
Our new security contact email is security@tidelift.com. :)
