### ISSUE TITLE
Bug in LazyOpenStream

### ISSUE THREAD

**Issue by DavidBruchmann** [guzzle/psr7#428]
`LazyOpenStream` defines only 2 methods of `Psr\Http\Message\StreamInterface` but is declared as final.  
https://github.com/guzzle/psr7/blob/148492f9e2e1524317a8aa60875f5b59517a9374/src/LazyOpenStream.php#L13

As final class it neither includes all methods of the interface, nor allows to be extended to satisfy the interface,

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Which methods are missing, please?

**Comment by DavidBruchmann** [comment]
The StreamInterface can be found here:
https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php

If the class is final, all method of the interface had to be defined.

Nevertheless, I doubt that the "final" is advisable, especially as TYPO3 is extending the class already:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Http/SelfEmittableLazyOpenStream.php

**Comment by DavidBruchmann** [comment]
Sorry, I must correct myself, all methods are existing, I did miss the trait.

Nevertheless, TYPO3 is extending the class, and the "final" is therefore disturbing.
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Http/SelfEmittableLazyOpenStream.php

It might be possible though that the according implementation in TYPO3 should be changed.

**Comment by DavidBruchmann** [comment]
The according issue in TYPO3 can be found here if it's of interest:  
https://forge.typo3.org/issues/94422

**Comment by GrahamCampbell** [comment]
Typo3 should make another class that implements that interface and takes a stream into he constructor, and then proxies calls. Composition over inheritance. :)

**Comment by DavidBruchmann** [comment]
Yes it's done just wrong in TYPO3 :)
