### ISSUE TITLE
strtolower() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by elmrace** [guzzle/psr7#429]
**PHP version**: 7.4.20

**Description**
Utils.php caselessRemove function was return "strtolower() expects parameter 1 to be string, int given" message

**Possible Solution**
Line 28: 
`if (!in_array(strtolower($k), $keys)) {`
TO
`if (!in_array(strtolower(strval($k)), $keys)) {`

then problem solved.

**Comment by GrahamCampbell** [comment]
It shouldn;t be called with an array with integer keys. When are you seeing this error?

**Comment by Tobion** [comment]
@elmrace can you give more details?

**Comment by KoenPasman** [comment]
I was seeing the same thing in using Guzzle with this header setting:

```php
'headers' => [
    'Content-Type: application/x-www-form-urlencoded',
],
```

But, with the new 2.0.0 version you need to pass it as an associative array:
```php
'headers' => [
    'Content-Type' => 'application/x-www-form-urlencoded',
],
```

**Comment by Tobion** [comment]
Also in v1 the headers are meant to be associative. See PSR-7 spec. If it worked before using `'Content-Type: application/x-www-form-urlencoded',` this was just by accident.

**Comment by KoenPasman** [comment]
Yes, so the solution would be to pass the headers as an associative array, not an array of strings.

**Comment by GrahamCampbell** [comment]
So actually it looks like other parts of the code allow numeric keys as header keys, so we should probably cast this. This won't fix your issue, though. You were calling the code wrong. ;)
