### ISSUE TITLE
ServerRequest: Use X-Forwarded-* headers for URL generation

### ISSUE THREAD

**Issue by cweiske** [guzzle/psr7#430]
**Description**
When the web server is running behind a proxy (like apache's mod_proxy or traefik, or a ssl-stripping one), the original URL can often not be deduced from `$_SERVER['HTTP_HOST']` and `$_SERVER['SERVER_PORT']`. The web server handling the request can be running on a different port, or is accessed with an internal host name.

Proxies send special HTTP headers "X-Forwarded-Host", "X-Forwarded-Port" and "X-Forwarded-Proto" (source: [apache mod_proxy](http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers), [traefik docker user guide](https://doc.traefik.io/traefik/v2.0/user-guides/docker-compose/basic-example/), [waitress reverse proxy setup](https://docs.pylonsproject.org/projects/waitress/en/stable/reverse-proxy.html), [elastic load balancing x-forwarded headers](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html), [TrustedProxy php lib](https://github.com/fideloper/TrustedProxy))

When running in such an environment, `GuzzleHttp\Psr7\ServerRequest` generates incorrect URLs.

It should take them into account instead of only relying on the standard `$_SERVER variables.

**Example**
HTTP request to `http://application:80/` with headers `X-Forwarded-Port: 443`, `X-Forwarded-Proto: https` and `X-Forwarded-Host: example.org` should generate the URL `https://example.org/`.

**Additional context**
It could be a security problem to trust those headers from anyone.
[Symfony](https://symfony.com/doc/current/deployment/proxies.html) and [Laravel](https://laravel.com/docs/8.x/requests#configuring-trusted-proxies) require one to define a list of trusted proxies. Only from their IP addresses, those headers are used.

More documentation:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

**Comment by Wirone** [comment]
It's for example visible in Sentry, because Sentry SDK uses `ServerRequest::fromGlobals()` in its `RequestFetcher` and URLs displayed in events are not correct (wrong proto and port).

**Comment by GrahamCampbell** [comment]
We cannot blanket use those forwarded for values because of security issues with bad actors setting those headers. I feel like you should change the host and proto headers yourself on the request object after creation, if you trust the source.

**Comment by GrahamCampbell** [comment]
I am not opposed to bringing this functionality into this package, but I don't want to change the behaviour of the existing API, so there'd need to be a new API for this. I'd happily review a PR to do this, but I am not going to implement this myself. @Nyholm do any other PSR implementations implement this?

**Comment by cweiske** [comment]
https://adam-p.ca/blog/2022/03/x-forwarded-for/
