### ISSUE TITLE
Unexpected breaking change between guzzle/psr7:1.7.0 and guzzle/psr7:1.8.0

### ISSUE THREAD

**Issue by SergeySmile** [guzzle/psr7#432]
**PHP version**: 7.4.21

**Description**
Hello guys. I encountered an unexpected breaking change between guzzle/psr7:1.7.0 and guzzle/psr7:1.8.0

It causes by https://github.com/guzzle/psr7/pull/354

My case:
I'm proxying some requests using php script.
Things go wrong while trying to proxy a request that download a file.

1. I'm handling client request using symfony-http-foundation component and the script input is \Symfony\Component\HttpFoundation\Request $request.
Client make a get request with empty body and doesn't send "content-length" header but
$request->headers->get("content-length") eq "" because by default PHP has $_SERVER["content-length"] = "" 

2. Then script create new \GuzzleHttp\Psr7\Request using request from step 1) to send it further using \GuzzleHttp\ClientInterface::send
Script expect that proxying request body always is resource:
$proxyRequest = new Psr7\Request($request->getMethod(), $request->getUri(), $request->headers->all(), $request->getContent(true));

3. After that \GuzzleHttp\ClientInterface::send($proxyRequest) is calling and after going through a bunch of stages,
it calls \GuzzleHttp\Handler\CurlFactory::create inside \GuzzleHttp\Handler\CurlHandler::__invoke where things are breaking inside applyMethod function

**with old 'php://input':**
$size = $body->getSize() will return null and then it will be called applyBody which will remove Content-Length header
$this->removeHeader('Content-Length', $conf);

**with new 'php://temp':**
$size = $body->getSize() will return 0 (because fstat is using and request body was empty) and then it will be not called applyBody and Content-Length header will not be removed

It turns out that which is quite unexpected:
- before the update of guzzle described request is proxing without "Content-length" header 
- after update described request is proxing with "Content-length" header

**How to reproduce**
I described problem above. If it is valuable - i will make a test scripts.

**Possible Solution**
For now i'm just checking "Content-length" header before in input point. If it has value eq "" - remove it from headers.

**Comment by GrahamCampbell** [comment]
Can you identify the PR that broke this so we can get some more context into why that change was made?

**Comment by GrahamCampbell** [comment]
If the request body is actually empty, then setting a zero content-length header is the correct behaviour here?
