### ISSUE TITLE
Invalid resource type: integer

### ISSUE THREAD

**Issue by marius-c** [guzzle/psr7#45]
Hey,

Any particular reason why `stream_for` function does not accept an integer ?

It throws that exception when using a parameter like:

```php
[
    'name' => 'event',
    'contents' =>  '1'
]
```

**Comment by mtdowling** [comment]
Passing '1' to stream_for works correctly. stream_for accepts the contents of the stream in the first argument: https://github.com/guzzle/psr7/blob/master/src/functions.php#L77
