### ISSUE TITLE
support php8.1

### ISSUE THREAD

**Issue by HillLiu** [guzzle/psr7#466]
## Error message
Deprecated: Return type of GuzzleHttp\Psr7\Uri::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /git/pmvcgit/s3/vendor/guzzlehttp/psr7/src/Uri.php on line 528

## Related code
https://github.com/guzzle/psr7/blob/master/src/Uri.php#L528-L531

**Comment by GrahamCampbell** [comment]
Thanks for the report. If you use the latest stable release, this bug is not present. This is only a temporary regression on master.
