### ISSUE TITLE
Suggest changing js mime type from text/javascript to application/javascript

### ISSUE THREAD

**Issue by phucwan91** [guzzle/psr7#473]
**PHP version**: 7.4.3

**Description**
as RFC 4329
https://www.iana.org/assignments/media-types/application/javascript
https://www.iana.org/assignments/media-types/text/javascript

should we change **js mime type** from `text/javascript` to `application/javascript` ?

or please explain the reason that we have to keep `text/javascript` !

**Comment by GrahamCampbell** [comment]
Would be resolved by https://github.com/guzzle/psr7/pull/453.
