### ISSUE TITLE
LimitStreamTest::testEnsuresPositionCanBeekSeekedTo()

### ISSUE THREAD

**Issue by fadimko** [guzzle/psr7#49]
https://github.com/guzzle/psr7/blob/master/tests/LimitStreamTest.php#L52

I don't know if it is a real issue, but do you know, that this test passes only because `Psr7\stream_for()` creates `'php://temp'` stream? Php tries to `fseek()` to non-existing offset and gets an error there https://github.com/guzzle/psr7/blob/master/src/Stream.php#L200.

But if `Psr7\stream_for()` called `fopen('<path to some file>', 'w');`, the test would fail, because
>In general, it is allowed to seek past the end-of-file; if data is then written, reads in any unwritten region between the end-of-file and the sought position will yield bytes with value 0.
https://php.net/manual/en/function.fseek.php

```
$stream = fopen('php://temp', 'r+');
echo fseek($stream, 10) . "\n";      <— -1

$stream = fopen('./fseek.file', 'w');
echo fseek($stream, 10) . "\n";      <— 0
```

I discovered this, when I tested PSR-7 on HHVM. In HHVM `fseek()` can go beyond the end-of-line in `'php://temp'` streams too, so this test fails. And now I don't know who's problem it is, and is it a problem at all.

Tested on Ubuntu 14.04, php 5.5.26, hhvm 3.9.1

**Comment by jeskew** [comment]
This sounds more like an issue with the test than an issue with the stream implementation. If a file handle allows you to seek past its end, then I don't think this library should be reporting that as a failure.

Maybe the test should be refactored so as not to rely on a `php://temp` streams implementation? It looks like this is the only test failing on HHVM on Travis.

**Comment by mtdowling** [comment]
Yeah, I think this is a bad test more than anything.

**Comment by Tobion** [comment]
I think the easiest solution is to skip the test on hhvm as the behavior is indeed different: https://3v4l.org/TXNdR
And I don't see a way to make the same test for both php and hhvm work.
