### ISSUE TITLE
Request Headers Validation issue in >= 2.1.1

### ISSUE THREAD

**Issue by ibrasho** [guzzle/psr7#490]
**PHP version**: 8.1.4

**Description**
It seems the 

**How to reproduce**
Building any request seems to trigger this issue.

**Possible Solution**
https://github.com/guzzle/psr7/blob/master/src/MessageTrait.php#L262
I'm assuming the inverse is the intention?

**Comment by it-can** [comment]
same as #489

**Comment by GrahamCampbell** [comment]
Closing since this is a duplicate.
