### ISSUE TITLE
Unable to use Microsoft Graph endpoints - "2.1.12570.11 - NCUS ProdSlices" is not valid header value

### ISSUE THREAD

**Issue by dinamic** [guzzle/psr7#499]
**PHP version**: 7.4

**Description**
We make use of Microsoft Graph endpoints and with the most recent version we've got the following exception to pop up:

```
"2.1.12570.11 - NCUS ProdSlices" is not valid header value
```

This change seems to be part of the recent changes:
- https://github.com/guzzle/psr7/compare/1.8.3...1.8.4

I have not checked the RFC about it, but it feels odd that we can't send those headers anymore.

Shouldn't the receiving side be validating them, not the sending one?

**Comment by GrahamCampbell** [comment]
Fixed in 1.8.5.
