### ISSUE TITLE
在src/MessageTrait.php的第226的Bug

### ISSUE THREAD

**Issue by misscx** [guzzle/psr7#501]
**PHP version**:7.2.23 (hint: `php --version`)

**Description**

src/MessageTrait.php的第226行，枚举了部份可以作为header的字符，我的请求header中包含”:“，结果出提示错误信息。修改了preg_match的正则表达式后可以正常运行。
**How to reproduce**

> $client = new GuzzleHttp\Client();
> $res = $client->request('GET', 'https://github.com', [
>     'query' => ['wd' => 'QueryList'],
>     'headers' => [
>         'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
>         'Accept-Encoding' => 'gzip, deflate, br',
>         ':test'=>'test',
>     ]
> ]);

**Possible Solution**

在src/MessageTrait.php的第226行preg_match函数中加入相应的需要验证的正则表达式。
**Additional context**

如：

>  if (! preg_match('/^[a-zA-Z0-9\'`#$%&*+.^_|~!-:]+$/', $header)) {
>             throw new \InvalidArgumentException(
>                 sprintf(
>                     '"%s" is not valid header name',
>                     $header
>                 )
>             );
>         }

**Comment by GrahamCampbell** [comment]
The header name you have there is invalid. The HTTP Spec forbids using a colon in the name of a header.
