### ISSUE TITLE
Integration Test Suite not actually executed in CI

### ISSUE THREAD

**Issue by TimWolla** [guzzle/psr7#506]
https://github.com/guzzle/psr7/runs/6256679863?check_suite_focus=true

In step "Run tests" it is reported that:

```
PHPUnit 9.5.20 #StandWithUkraine

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

No tests executed!
```

Should this:

https://github.com/guzzle/psr7/blob/58a607de30248bdbb28655d5d46661de5efd727c/.github/workflows/integration.yml#L42

be `./vendor/bin/phpunit --testsuite "Guzzle PSR-7 Integration Test Suite"` instead?

**Comment by GrahamCampbell** [comment]
Oops, that's probably my bad.

**Comment by TimWolla** [comment]
I don't plan on creating a PR for this, as I am not sure how you prefer to handle `PSR-7 Integration Test Suite`, also I'm not super experienced with PHPUnit. So please handle this yourself, thanks!
