### ISSUE TITLE
Uri cannot be constructed for URI reference of absolute path with colon and numbers

### ISSUE THREAD

**Issue by hlubek** [guzzle/psr7#526]
**PHP version**: x.y.z (hint: `php --version`)

8.1.4 (but also reproduced in 8.0, 7.4)

**Description**

A `Uri` cannot be constructed for a specific URI reference (consisting only of a path, used for imgproxy).
It is a valid URI reference though (by applying the regular expression from RFC 3986 and testing with other languages).

**How to reproduce**

```php
<?php

use GuzzleHttp\Psr7\Uri;

$uri = new Uri('/_img/Lkc9WXxgdKTzoqaupsmHX6OpgIagQrg0GS8DcoLhUSg/fn:2/q:75/rs:fit:250:250:0:0/czM6Ly9yZWdlbmJvZ2VuLW5lb3MvbmVvcy9yZXNvdXJjZXMvcGVyc2lzdGVudC81MGRlNDg3YTE0NGNjNDZmZmI4OWY1OTczM2ZhNDhiNWY5N2FmNjI4');
// Fatal error: Uncaught GuzzleHttp\Psr7\Exception\MalformedUriException: Unable to parse URI: ...
```

If `fn:2` is replaced by `fn:some-filename`, the URI reference can be parsed:

```php
<?php

use GuzzleHttp\Psr7\Uri;

$uri = new Uri('/_img/Lkc9WXxgdKTzoqaupsmHX6OpgIagQrg0GS8DcoLhUSg/fn:some-filename/q:75/rs:fit:250:250:0:0/czM6Ly9yZWdlbmJvZ2VuLW5lb3MvbmVvcy9yZXNvdXJjZXMvcGVyc2lzdGVudC81MGRlNDg3YTE0NGNjNDZmZmI4OWY1OTczM2ZhNDhiNWY5N2FmNjI4');
```

**Possible Solution**

The path component `fn:2` seems to be misinterpreted as the port of an authority by `parse_url`.
There might be other cases where URIs and URI references are not correctly parsed by `parse_url` according to the notes on https://www.php.net/manual/en/function.parse-url.php.

Using a regular expression based on the example in RFC 3986 might be a viable substitution.

**Comment by GrahamCampbell** [comment]
I think this is because the path you've provided contains invalid characters - you can't use a colon. Replace all the colons with `%3A` and it should work.

**Comment by hlubek** [comment]
> 

Hi, thanks for the swift reply!

Well, it is not invalid according to https://datatracker.ietf.org/doc/html/rfc3986#appendix-A which includes colons for path segments in this scenario. I would expect `Uri` to be standards compliant here.

Additionally it's not that colons generally cause this issue. It's only if paired with a number - I guess it's because `parse_url` is just not meant for URIs but only full URLs and gets confused by an apparent host / port.

**Comment by GrahamCampbell** [comment]
There's not much other option if you want to not pass a valid URI through to the Url class. Parse URL is not mis-interpreting it - it just is not meant to be given just a path. ;)
