### ISSUE TITLE
Code issue in LimitStream

### ISSUE THREAD

**Issue by spemed** [guzzle/psr7#530]
**Description**
Whether the tell method in LimitStream should differentiate the situation that property $limit not equal -1 ?

**Example**
+ The origin code in newest branch master is 

```
public function tell(): int
{
    return $this->stream->tell() - $this->offset;
}
```

+ In my opinion, the code about tell method should be 

```
public function tell(): int
{
    $hasLimit = $this->limit !== -1;
    $diff = $this->stream->tell() - $this->offset;
    return $hasLimit ? min($diff,$this->limit) : $diff;
}
```

**Additional context**
If I'm not thinking well, could you please explain why the original code was designed this way?

**Comment by GrahamCampbell** [comment]
I don't think it's permitted to use a negative limit value?

**Comment by spemed** [comment]
> 

Ok, i got it. The `read` method in `LimitStream` guarantee that the underlying stream `tell` method will not beyond `$this->offset + $this->limit`. Thanks you for your response.
