### ISSUE TITLE
Relative URI > Can't parse_url if colon is present

### ISSUE THREAD

**Issue by mihai-stancu** [guzzle/psr7#56]
When using **relative** URIs they are sent to the Uri constructor and `parse_url` is called to extract information from them.

> **Conditions:**
> If the path contains a **colon**.
> ...and what comes after the **colon** character must be numeric.
> ...and number of numeric characters after the colon is < 6.
> ...in other words if it *"kinda looks like a port number"*...
> ...and there are no **query parameters**.
> ...and there is no **fragment**.
> ...and there are no previous occurrences of the  **colon** sign.

...then `parse_url` will fail to recognize the path component and return `false`

```php
    // Psr\Http\Message\UriInterface\Uri

    public function __construct($uri = '')
    {
        if ($uri != null) {
            $parts = parse_url($uri);
        ....

    }

    ...

    public static function resolve(UriInterface $base, $rel)
    {
        ...

        if (!($rel instanceof UriInterface)) {
            $rel = new self($rel);
        }

        ....

    }
```

You can reproduce the issue via:

```php
$client = new GuzzleHttp\Client(['base_uri' => 'http://example.com:90/']);
$client->request('get', '/a/b/c/d/e:12345');
```

**Comment by mtdowling** [comment]
Can you provide a concrete example?

Please note thought that one of the things I want to avoid is having to implement a custom URI parser to account for things like this. It would be slow and would be a maintenance burden. If this ends up being a limitation of PHP's parse_url, then I think we would just chalk it up as a "known issue".

**Comment by mihai-stancu** [comment]
I've experimented some more and found even more constraints to the condition. Now I'm pretty sure this should be a known issue.

I'll update the initial description with the further constraints and an example.

**Comment by mihai-stancu** [comment]
Should I close the issue or will you close it with a particular status/label?

**Comment by mtdowling** [comment]
Hm... I wonder if there's something we can do here, at least for the case of combining URIs... For example, maybe we can have a special case for combining with a relative URI that starts with '/'?

**Comment by mihai-stancu** [comment]
Simple fix would be (in the context of initializing relative paths) to add a question mark if one is not already present.

**Comment by Tobion** [comment]
Is there a PHP bug report for this? https://3v4l.org/QMNeo definitely seems like a PHP bug.

**Comment by mihai-stancu** [comment]
@Tobion not one that I found but `parse_url` might very well have been intended to parse complete URLs (containing scheme, authentication, domain, tld, port, path, query, fragment, etc.).

Using `parse_url` for relative paths could be regarded as improper usage. Which is why I didn't pursue it as a PHP bug per se.

**Comment by Tobion** [comment]
But it parses relative urls correctly for the most part like `//example.org` and `/path`. So either it parses only absolute URIs and needs to return false for anything else. Or it must parse relative URIs correctly as well.
