### ISSUE TITLE
GuzzleHttp\Psr7\Message::bodySummary() incorrect cut off characters in unicode encoding

### ISSUE THREAD

**Issue by K1SsLoID** [guzzle/psr7#561]
**PHP version**: 7.4.33

**Description**
When using the method `GuzzleHttp\Psr7\Message::bodySummary()`, characters in unicode encoding may be incorrectly cut off.

**How to reproduce**
Server error: \`POST [https://1cfresh.com/a/httpextreg/hs/ExternalRegistration/register\`](https://1cfresh.com/a/httpextreg/hs/ExternalRegistration/register) resulted in a \`500 Internal server error\` response: ﻿{HTTPСервис.ExternalRegistration.Модуль(24)}: Индекс находится за границами м\xD0 (truncated...)

**Possible Solution**
Аfter truncating a string, remove invalid characters from it:
`implode('', array_filter(mb_str_split($needleString), 'mb_ord'))`

**Additional context**

**Comment by GrahamCampbell** [comment]
I don't want to add a dependency on ext-mb, though this issue should be somewhat fixed in v2.4.5 and v2.5.0 due to https://github.com/guzzle/psr7/commit/3f849aa7a8063828d8f68e652758f68683bf14a2
