### ISSUE TITLE
Missing typehints

### ISSUE THREAD

**Issue by neforce** [guzzle/psr7#562]
**PHP version**: 7.2.33 (and others)

**Description**
I'm encountering many errors with version 2.5 and psr/http-message 2.0.

http-message 2.0 contains typehints which doesn't occur in 2.5. 

**How to reproduce**
Try running these versions.

**Possible Solution**
Enter typehints for many functions. It takes a lot of time....

Example given:
https://github.com/guzzle/psr7/blob/2.5/src/Request.php function withUri does not contain 'bool' as typehint.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. We are aware of this, and this is not a bug (https://3v4l.org/u3JDE). We will be adding types in v3.
