### ISSUE TITLE
GuzzleHttp\Psr7\Uri Incorrectly filled port, when converted to a string

### ISSUE THREAD

**Issue by 413f** [guzzle/psr7#563]
**PHP version**: 8.2.7 

**Description**
Incorrect port filtering for url in `\GuzzleHttp\Psr7\Uri::filterPort`

**How to reproduce**
Call the `\GuzzleHttp\Psr7\ServerRequest::getUriFromGlobals()` function if `$_SERVER['SERVER_PORT']` contains an empty string and `$_SERVER['HTTP_HOST']` does not contain a port.
In the case when the port is empty, null is converted to 0 and we get the link `https://mysite.com:0/`

**Possible Solution**

https://github.com/guzzle/psr7/blob/815698d9f11c908bc59471d11f642264b533346a/src/ServerRequest.php#L223
Change validation to `if (!$hasPort && $_SERVER['SERVER_PORT']) {`

**Additional context**

**Comment by GrahamCampbell** [comment]
When does server port ever contain an empty string?

**Comment by 413f** [comment]
Sorry my mistake. Should not be an empty string, found where assigned.
