### ISSUE TITLE
Content-Type assumption not done if the file don't have extension

### ISSUE THREAD

**Issue by ReiatsuSan** [guzzle/psr7#567]
**PHP version**: x.y.z (hint: `php --version`)

**Description**
There is an issue within psr7 in the MultipartStream class inside createElement method (https://github.com/guzzle/psr7/blob/815698d9f11c908bc59471d11f642264b533346a/src/MultipartStream.php#L141C1-L141C1).
There is an assumption a content-type is returned no matter what...

**How to reproduce**
Try to upload a multipart file without extension

**Possible Solution**
Add a default content-type for files without extensions l'île proposes in PR  #566

**Additional context**

**Comment by GrahamCampbell** [comment]
It doesn't assume that? The `if ($type = MimeType::fromFilename($filename)) {` will skip if there's no type.

**Comment by GrahamCampbell** [comment]
Do we have to supply a default content type, if none makes sense?

**Comment by ReiatsuSan** [comment]
Imho If no Content-Type could be determined application/octet-stream or anything like this seams a good fit.
As a user of guzzler to create my multipart requests does not let me change the content header. If there is a solution to set the Content-Type without loosing the boundary field I am ok with leaving the current behaviour...

**Comment by GrahamCampbell** [comment]
Fixed in 2.6.0.
