### ISSUE TITLE
$response->getBody()->getContents() returns empty string

### ISSUE THREAD

**Issue by enumag** [guzzle/psr7#569]
**PHP version**: 8.2.5

**Description**
`$response->getBody()->getContents()` returns empty string for me. `(string) $response->getBody()` works correctly.

**How to reproduce**
No special configuration.

**Possible Solution**
I checked `$response->getBody()` and it's an instance of `\GuzzleHttp\Psr7\Stream`. It seems the key difference is that __toString calls seek while getContents does not. Is there a reason for that? Maybe the seek call should be simply moved into getContents?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is expected behaviour. `getContents` does not rewind the stream for compatibility with the original PSR spec. This may be changed in the next major version so that it rewinds. `(string) $response->getBody()` is for sure what you want if you want to get the whole body as a string.

**Comment by enumag** [comment]
That still doesn't make it clear why the stream isn't at the beginning. I didn't do anything with $response other than checking the status code so I'd expect the stream to be at position 0 by default. Why isn't it?

**Comment by GrahamCampbell** [comment]
Probably you have a middleware that is reading the stream or some code that already called getContent.

**Comment by enumag** [comment]
Yeah you're right. It's because during code review one of my colleagues asked me to add this:

```php
        $stack->push(
            \GuzzleHttp\Middleware::log(
                $this->logger,
                new \GuzzleHttp\MessageFormatter(\GuzzleHttp\MessageFormatter::DEBUG),
                \Psr\Log\LogLevel::DEBUG,
            ),
        );
```

MessageFormater reads the body without rewinding it afterwards so that caused the problem.
