### ISSUE TITLE
AAC MimeType has a Typo

### ISSUE THREAD

**Issue by Nulledmind** [guzzle/psr7#571]
**PHP version**: 8.1.21 

**Description**
There is a typo with the AAC MimeType in 

https://github.com/guzzle/psr7/blob/815698d9f11c908bc59471d11f642264b533346a/src/MimeType.php#L21

**How to reproduce**
View the /src/MimeType.php file, line 21

**Possible Solution**
It should be (unless there's been some change I'm not aware of to this mimetype in general)
`        'aac' => 'audio/x-aac',`

**Additional context**
It appears to have been pulled in via generation with the typo from 
https://github.com/thephpleague/mime-type-detection/blob/main/src/GeneratedExtensionToMimeTypeMap.php

**Comment by GrahamCampbell** [comment]
Are you able to file an issue upstream please?

**Comment by Nulledmind** [comment]
> Are you able to file an issue upstream please?

I'm not quite sure what you mean by that, my apologies.

**Comment by GrahamCampbell** [comment]
This repo: https://github.com/thephpleague/mime-type-detection. We just pull from that, so when they update their list, we'll sync up.

**Comment by Nulledmind** [comment]
Ahh okay, gotcha. Will do. Thank you

**Comment by GrahamCampbell** [comment]
I'm going to make the fix on our side, anyway.
