### ISSUE TITLE
Remove ralouphie/getallheaders dependency ?

### ISSUE THREAD

**Issue by alamirault** [guzzle/psr7#572]
Hello,

On https://github.com/ralouphie/getallheaders description it's wrote 
> PHP getallheaders() polyfill. Compatible with PHP >= 5.3.

As this package require `7.2.5 || ^8.0`, this package shouldn't be removed in `require` section ? 

I'm not 100% due to this comment on original PR

> It does a few extra things like Authorization headers.
https://github.com/guzzle/psr7/pull/162#issuecomment-349832006

Can you clarify this part ?

**Comment by GrahamCampbell** [comment]
I don't understand what you are objecting to? That package works fine with all PHP versions we support.

**Comment by alamirault** [comment]
My objective ? Minimize my vendor size if some package are not really needed

**Comment by GrahamCampbell** [comment]
If you want to force it not to be included in your app vendor, you can mark your app as "replacing" the package. I do this all the time with the symfony pollyfills.

```
    "replace": {
        "paragonie/random_compat": "*",
        "paragonie/sodium_compat": "*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-intl-grapheme": "*",
        "symfony/polyfill-intl-icu": "*",
        "symfony/polyfill-intl-idn": "*",
        "symfony/polyfill-intl-normalizer": "*",
        "symfony/polyfill-mbstring": "*",
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*",
        "symfony/polyfill-php82": "*"
    },
```

etc.

**Comment by GrahamCampbell** [comment]
Though if you do this and there is code that is used that calls it, you will run into problems.

**Comment by alamirault** [comment]
Thanks, not the best but it will be enough for my case

**Comment by GromNaN** [comment]
The package looks unmaintained. There are open pull requests from 2019 that didn't get any attention. The last release is 6 years old. The owner is not active on GitHub.

You could import the single file of this package in this project. (I can open a PR if you agree with the principle).

**Comment by GrahamCampbell** [comment]
So far, there's no need. There are no upstream changes, because none are needed. The code is small and already works great. I'm not in a rush to ditch it at this time.

**Comment by iruoy** [comment]
In PHP 7.3, the `getallheaders()` function was updated to work with PHP-FPM. Therefore, when the minimum required PHP version is upgraded to 7.3, a polyfill will no longer be necessary. Until then, it is needed.

However, I would also like to see this inlined due to the risk of supply chain attacks.
