### ISSUE TITLE
Declaration Error in GuzzleHttp\Psr7\Uri because of missing type hint for arguments.

### ISSUE THREAD

**Issue by MarioWMan** [guzzle/psr7#587]
**PHP version**: PHP 7.1.33

**Description**
Declaration of GuzzleHttp\Psr7\Uri::withScheme($scheme): Psr\Http\Message\UriInterface must be compatible with Psr\Http\Message\UriInterface::withScheme(string $scheme)

The error message should be enough to understand what's the problem here. ;-)
It is not only on this function!

**How to reproduce**
Every time, if I try to execute an php wich includes this class.

**Possible Solution**
The functions in Uri class should also have type hint's for the arguments like it is in the interface class.

**Additional context**
Could be it is only in E_STRICT mode, but I expect it should work in each modes!

**Comment by GrahamCampbell** [comment]
This is happening because you are using PHP 7.1, which is not supported.

**Comment by GrahamCampbell** [comment]
Or at least, you have installed dependencies using composer, using a higher version of PHP, which resulted in you having code loaded that doesn't work properly on PHP 7.1. If you run composer on PHP 7.1 instead (making sure to not ignore the php version constraints), then there is an older version of this package and the psr contracts that will work on PHP 7.1.

**Comment by MarioWMan** [comment]
Hello and thx for the quick response!
Yes I saw it, that it works in PHP 7.4 for example. But my production system is currenty running with PHP 7.1.

But in generally, I guess it should be a clear wholeformed code, so I would make the functions compatible with the interface and I guess no more issues will be happen because of this.

BR, merry xmas and happe new year! ;-)

**Comment by GrahamCampbell** [comment]
> so I would make the functions compatible with the interface and I guess no more issues will be happen because of this.

The method definitions are compatible of newer PHP, but not PHP 7.1. As such, there are no changes for us to make here. One should always install packages using the same PHP version as the one you want to use in production. This will just be the first of a long line of issues you will encounter when running PHP code intended for PHP 7.4 on PHP 7.1

**Comment by GrahamCampbell** [comment]
There is good reason why the methods are not identical with the interfaces - it's because we support two different major versions of the psr interfaces at the same time.
