### ISSUE TITLE
Cross Origin - Allow optional protocol upgrade

### ISSUE THREAD

**Issue by noefleury** [guzzle/psr7#590]
**PHP version**:

Every compatible versions : `^7.2.5 || ^8.0`.

**Description**

When we are checking if a modified URL should be considered as `cross-origin` (eg: during a request which resulted on an HTTP 301), we are checking 3 things, see [Same-Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

I understand that it's a security check, but as this package is used on the backend and not on the frontend, I think we should let the user the ability to authorize a scheme and port upgrade, which means an unsecured (http/80) redirection to a secure request (https/443). Of course, if the host is altered during the redirection, the check will still pass.

**Additional informations**

Before, a check of the same kind was made in Guzzle using the [host only](https://github.com/guzzle/guzzle/commit/cc80b002a0c550d242e20ed28ef52b35e237e0c9#diff-cad2882c588ac6521c01f469efa0c921c047c14be51ed4e9481ec4d5ed6bd238R92).

**Possible Solution**

Add an optional flag in the `UriComparator::isCrossOrigin` method.

**Comment by GrahamCampbell** [comment]
I don't think we want to allow upgrade. It is a security mistake to send the confidential data over plain text then get upgraded to https. We also are mimicking how other major projects handle this, such as curl.

**Comment by noefleury** [comment]
So maybe we should have the ability to [fully bypass this check](https://curl.se/docs/manpage.html#--location-trusted) too ? In that case the issue is more linked to `Guzzle` itself, and no more linked to `psr7`.

**Comment by GrahamCampbell** [comment]
I suppose this ability does exist if you implement and use your own redirect middleware without the cross-origin check. I am somewhat hesitant to build this natively into Guzzle, given how edge case this use case is, and how easy it is to use our middleware system to get custom behaviour.

**Comment by noefleury** [comment]
You're right about it, that's in fact an edge case. I'll close the issue and the linked PR.

Thanks 👍
