### ISSUE TITLE
Header validation (InvalidArgumentException : ":<header>" is not valid header name)

### ISSUE THREAD

**Issue by guram-vashakidze** [guzzle/psr7#597]
**Description**
There aren't way to use "not valid" headers (which isn't follow RFC7230). In my app I'm implementing app push notification trough [APNS](https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns). This API is using headers: `:method`, `:path`, `:scheme`.

**Solutions**
1. Add option `disable_header_validation` - to disable [assertHeader](https://github.com/guzzle/psr7/blob/45b30f99ac27b5ca93cb4831afe16285f57b8221/src/MessageTrait.php#L220) method
2. Add option `header_regex` - to change default regex `/^[a-zA-Z0-9\'`#$%&*+.^_|~!-]+$/D`
3. Add option `header_validation` - with closure which overwrite [assertHeader](https://github.com/guzzle/psr7/blob/45b30f99ac27b5ca93cb4831afe16285f57b8221/src/MessageTrait.php#L220) method

**Comment by GrahamCampbell** [comment]
Does their API work if you encode the `:` as `%3A`?

**Comment by GrahamCampbell** [comment]
Actually, I think you are misunderstanding the spec you linked to. You are not supposed to add the `:method` etc headers as real headers. Those are pesudo-headers as part of HTTP/2. You need to set these values as the native method, path and schema on our request object, not as headers.

**Comment by GrahamCampbell** [comment]
See https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.3.

**Comment by guram-vashakidze** [comment]
@GrahamCampbell Unfortunately these are the request headers not request body (also `%3A` - not working) - it's clear from their doc and I checked it. 
I implement it on native cURL lib and it works.

**Comment by GrahamCampbell** [comment]
Their doc says to use HTTP/2. cURL is for sure correcting your mistake and not using those as real headers for you.

**Comment by GrahamCampbell** [comment]
If it's "not working", likely you need to instruct Guzzle to use HTTP/2. By default it will only use 1.0 or 1.1.
