### ISSUE TITLE
Allowed memory size of nnnnnn bytes exhausted

### ISSUE THREAD

**Issue by the-djmaze** [guzzle/psr7#65]
PSR-7 has an issue. https://evertpot.com/psr-7-issues
Some people i helped abandoned Guzzle due to this bug.
Try it yourself with an 1GB file and send a partial stream.

```
$stream = GuzzleHttp\Stream\Stream::factory(fopen($path, 'r'));
$stream->seek($offset);
while (!$stream->eof()) {
    echo $stream->read($length);
}
$stream->close();
```

**Comment by mtdowling** [comment]
The library you're using in your example is not Guzzle's PSR-7 library but an older version of Guzzle.

**Comment by the-djmaze** [comment]
Ah that explains it. Thanks i will notify them.
