### ISSUE TITLE
InflateStream doesn't appear to allow incremental reading

### ISSUE THREAD

**Issue by patsplat** [guzzle/psr7#66]
Couldn't read incrementally from an InflateStream:

```php
$content = fopen(__DIR__.'/InflateStreamTestData.txt.gz', 'rb');
$a = Psr7\stream_for($content);
$b = new InflateStream($a);
$this->assertEquals('Nulla voluptate qui consectetur cillum consectetur.', $b->read(51));
```
Is this a miss-use of the API?  Or is this a bug?  Missing feature?

If one of the later, please provide direction so I can work on the pull request.

Test case here: https://github.com/patsplat/psr7/commit/daac696f71322b9b466f107e22aa0d091e576e43

**Comment by mtdowling** [comment]
I just merged a PR that might fix this for you: https://github.com/guzzle/psr7/pull/60

Can you try this again using the tip of master?

**Comment by patsplat** [comment]
Yes #60 passes.  Would you like another TestCase?  Should I PR?

**Comment by patsplat** [comment]
Otherwise feel free to close.  Thanks!
