### ISSUE TITLE
I'd like Uri to be a little more explicit with port numbers

### ISSUE THREAD

**Issue by timmillwood** [guzzle/psr7#67]
When doing the following, I'd expect it to return 80.
```
$uri = new Uri('http://example.com/foo/bar');
return $uri->getPort();
```

Or if not then I should very much expect it when doing this.
```
$uri = new Uri('http://example.com/foo/bar');
return $uri->withPort(80)->getPort();
```

**Comment by Tobion** [comment]
According to PSR-7 this should not happen.

> If the port is the standard port used with the current scheme, this method SHOULD return null.

So this issue can be closed.

**Comment by timmillwood** [comment]
Maybe I need a word with the PHP-FIG.

**Comment by Tobion** [comment]
I don't think it's a problem as it is per RFC 3986 that the port should be removed when it's the default.
And in the end it should not matter as the URIs are equal. And as a consumer you need to handle both `null` and the default port anyway from `getPort` as either can happen.

**Comment by timmillwood** [comment]
Right, currently I'm doing
```
$port = $uri->getPort();
if (empty($port)) {
    $port = ($uri->getScheme() == 'https') ? 443 : 80;
}
```

**Comment by Tobion** [comment]
If you need the actual port, this is the way to go.
