### ISSUE TITLE
Stream::getSize() should return null with popen streams

### ISSUE THREAD

**Issue by Rudloff** [guzzle/psr7#79]
Hello,

I am trying to work with popen streams like this:
```php
$stream = \GuzzleHttp\Psr7\stream_for(
    popen(
        'ls', 'r'
    )
);
```

But `$stream->getSize()` always returns 0 which causes problems with the Slim framework (see https://github.com/slimphp/Slim/issues/1838).

PSR-7 says that  `getSize()` should return null when the size is unknown, which seems to be the case here.

**Comment by mtdowling** [comment]
From what I understand, if popen streams return a valid size when calling fstat, then this would work.

How would Guzzle know it's a popen stream and not to trust the result of fstat?

**Comment by Rudloff** [comment]
I thought `stream_get_meta_data()` would return a different type for popen streams but it returns the same type as local file streams.
So indeed there might not be a way to detect that it is a popen stream.

**Comment by mtdowling** [comment]
Closing as this does not seem possible.

**Comment by llvdl** [comment]
Should this be reopened, since a solution is proposed in issue #1838?

**Comment by iget-master** [comment]
I agree that this should be reopened and implement the proposed solution.
