### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by harikt** [guzzle/psr7#8]
Hi, 

I was going through the guzzle code, have a doubt regarding the implementation 

https://github.com/guzzle/psr7/blob/0c7997709bb6079658c6091ffec6f1d47240375c/src/MessageTrait.php#L99

Doesn't it need to preserve the case sensitivity? See

https://github.com/php-fig/http-message/blob/f3218d1cdf479cd9a65d568f605edbc17c6df82a/src/MessageInterface.php#L118

```
While header names are case-insensitive, the casing of the header will be preserved by this function, and returned from getHeaders()
```

and I am seeing https://github.com/guzzle/psr7/blob/0c7997709bb6079658c6091ffec6f1d47240375c/src/MessageTrait.php#L42

```php
public function getHeaders()
{
    return $this->headerLines;
}
```

I understand it finally is returning the preserved value. But does `headerLines` in headers is a bit confusing? I wished the variable name is like 

```php
public function getHeaders()
{
    return $this->headers;
}

public function getHeaderLines()
{
    return $this->headerLines;
}
```

Thank you

**Comment by mtdowling** [comment]
This repo hasn't been updated to reflect recent changes to psr-7. We hope to get to it soon though.

**Comment by harikt** [comment]
Thank you @mtdowling for the fast reply.

**Comment by mtdowling** [comment]
Everything should now be up to date
