### ISSUE TITLE
Unable to read response's body contents

### ISSUE THREAD

**Issue by SilverFire** [guzzle/psr7#95]
Commit https://github.com/guzzle/psr7/commit/45054d91c290de494549511e470ef5853f726a50#diff-f89246dce7e387482b2c6c584a5e7e9dR97 have introduced a bug by comparing `$body` with empty string.

I did not dug too deeply to find out the real reason of wrong behavior, but I guess it is caused by implicit calling of `GuzzleHttp\Psr7\Stream::__toString()` in order to cast object to string to make a comparison.

### How to reproduce

```php
        $client = new \GuzzleHttp\Client(['base_uri' => 'https://google.com.ua/']);
        $response = $client->request('GET');
        $html = $response->getBody()->getContents();
```

### What is expected

`$html` contains a response HTML

### What do we have instead

`$html` is an empty string

### Patch?

Rolling back that line to `if ($body !== null)` fixes the problem. Not sure whether it is a proper fix.

### Environment

PHP 5.6.20
Ubuntu 16.04
guzzle/psr7@dev-master

**Comment by SilverFire** [comment]
Merging commit: https://github.com/guzzle/psr7/commit/28d8dbf50cca47882af6bab1f916521b8db92c8c

**Comment by FlorianKoerner** [comment]
Same issue here

**Comment by mtdowling** [comment]
Yes, this appears to be a regression that will need to be reverted.

**Comment by Tobion** [comment]
I'm fixing this.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by Tobion** [comment]
See #96

**Comment by BenBezac** [comment]
Was looking for a solution all the day and found this issue ;x

I rolled back to 1.3. and now i wait for the update ;)

**Comment by Tobion** [comment]
I'm kinda surprised that so many developers seem to be relying on an unreleased, unstable version.
