### ISSUE TITLE
StreamWrapper::stream_cast() 

### ISSUE THREAD

**Issue by hutnikau** [guzzle/psr7#98]
I'm using [dropbox-sdk](https://github.com/dropbox/dropbox-sdk-php) to upload files to the dropbox storage. This lib uses `CURLOPT_INFILE` curl option with resource as value to send file. 
https://github.com/dropbox/dropbox-sdk-php/blob/master/lib/Dropbox/Client.php#L291
It assumes that `StreamWrapper::stream_cast()` must be implemented.

I decided extend `\GuzzleHttp\Psr7\StreamWrapper` class to add `stream_cast()` method but I found that I can't get stream resource which should return `stream_cast()`.

I created such hack, but I'm not really happy with it:

``` php
public function stream_cast($cast_as)
{
    $clonedStream = clone($this->stream);
    return $clonedStream->detach();
}
```

What do you think about implementation of `StreamWrapper::stream_cast()` method?

**Comment by Tobion** [comment]
LGTM. Can you create a PR with tests please?
